// GENERATED by scripts/sync-workspace-cli.mjs — edit lib/protocol/ instead.
export const HELI_CAPABILITY_NAMES = Object.freeze([
	"session_start",
	"pre_tool",
	"post_tool",
	"permission_request",
	"subagent_start",
	"subagent_stop",
	"compaction",
	"structured_tool_input",
	"sandbox_attestation",
	"worktree_isolation",
]);

export const HELI_CAPABILITY_EFFECTIVE_STATES = Object.freeze([
	"unsupported",
	"documented",
	"wired",
	"observed",
	"enforced",
	"host-enforced",
]);

const CAPABILITY_NAMES = new Set(HELI_CAPABILITY_NAMES);
const EFFECTIVE_STATES = new Set(HELI_CAPABILITY_EFFECTIVE_STATES);

function error(code, capability, message) {
	return { code, capability, message };
}

/**
 * Validate the shape of a host capability map without inferring runtime proof.
 * A claim may describe package knowledge (`declared`), current-session evidence
 * (`observed`), and the strongest truthful guarantee (`effective`) separately.
 */
export function validateCapabilityMap(capabilities) {
	const errors = [];
	if (!capabilities || typeof capabilities !== "object" || Array.isArray(capabilities)) {
		return {
			valid: false,
			errors: [error("CAPABILITIES_NOT_OBJECT", null, "capabilities must be an object")],
		};
	}

	for (const [name, claim] of Object.entries(capabilities)) {
		if (!CAPABILITY_NAMES.has(name)) {
			errors.push(error("UNKNOWN_CAPABILITY", name, `unknown capability: ${name}`));
			continue;
		}
		if (!claim || typeof claim !== "object" || Array.isArray(claim)) {
			errors.push(error("INVALID_CAPABILITY_CLAIM", name, "capability claim must be an object"));
			continue;
		}
		if (claim.declared != null && typeof claim.declared !== "boolean") {
			errors.push(
				error("INVALID_CAPABILITY_DECLARED_FLAG", name, "declared must be boolean when present"),
			);
		}
		if (claim.observed != null && typeof claim.observed !== "boolean") {
			errors.push(
				error("INVALID_CAPABILITY_OBSERVED_FLAG", name, "observed must be boolean when present"),
			);
		}
		if (claim.effective != null && !EFFECTIVE_STATES.has(claim.effective)) {
			errors.push(
				error(
					"INVALID_CAPABILITY_EFFECTIVE_STATE",
					name,
					`invalid effective state: ${claim.effective}`,
				),
			);
		}
		if (claim.evidence != null) {
			if (!Array.isArray(claim.evidence) || claim.evidence.some((item) => typeof item !== "string")) {
				errors.push(
					error("INVALID_CAPABILITY_EVIDENCE", name, "evidence must be an array of strings"),
				);
			}
		}
	}

	return { valid: errors.length === 0, errors };
}
