// GENERATED by scripts/sync-workspace-cli.mjs — edit lib/protocol/ instead.
export const HELI_DECISION_EFFECTS = Object.freeze(["allow", "deny", "require-approval", "reroute"]);

/**
 * Stable codes that Heli core emits today plus protocol-level codes used when a
 * legacy guard does not yet provide a more specific identity. The protocol does
 * not reject unknown non-empty codes: host adapters and newer core versions may
 * introduce a code before an older consumer updates its vocabulary.
 */
export const HELI_DECISION_CODES = Object.freeze([
	"ALLOW",
	"CONCURRENT_BOOTSTRAP",
	"NO_SESSION",
	"UNBOUND_SESSION",
	"NOT_WRITE_MODE",
	"MALFORMED_LEASE",
	"STALE_LEASE",
	"LEASE_HELD",
	"NO_LEASE",
	"TIER_BLOCKED",
	"TIER_APPROVAL_REQUIRED",
	"ENV_WRITE_DENIED",
	"REMOTE_PUSH_DENIED",
	"TASK_GATE_DENIED",
	"PLAN_GATE_DENIED",
	"DIAGNOSIS_STATE_INVALID",
	"DIAGNOSIS_REROUTE_REQUIRED",
	"EXPENSIVE_RETRY_DENIED",
	"HUMAN_APPROVAL_REQUIRED",
	"GOVERNANCE_DENIED",
]);

const EFFECTS = new Set(HELI_DECISION_EFFECTS);

export function makeDecision({
	code,
	effect,
	rule = null,
	source = null,
	taskId = null,
	sessionId = null,
	details = null,
} = {}) {
	if (typeof code !== "string" || !code.trim()) {
		const error = new Error("decision code must be a non-empty string");
		error.code = "INVALID_DECISION_CODE";
		throw error;
	}
	if (!EFFECTS.has(effect)) {
		const error = new Error(`invalid decision effect: ${effect}`);
		error.code = "INVALID_DECISION_EFFECT";
		throw error;
	}
	const decision = {
		code: code.trim(),
		effect,
		rule: rule || null,
		source: source || null,
		taskId: taskId || null,
		sessionId: sessionId || null,
	};
	if (details != null) decision.details = details;
	return decision;
}

/**
 * Add Protocol v1 structured decision metadata to an existing hook result while
 * retaining every legacy field (`deny`, `reason`, `code`, `ctx`, etc.).
 */
export function withStructuredDecision(result, {
	code = null,
	effect = null,
	rule = null,
	source = "heli",
	details = null,
} = {}) {
	const legacy = result && typeof result === "object" ? result : {};
	const resolvedCode = code || legacy.code || (legacy.deny ? "GOVERNANCE_DENIED" : "ALLOW");
	const resolvedEffect = effect || (legacy.deny ? "deny" : "allow");
	return {
		...legacy,
		decision: makeDecision({
			code: resolvedCode,
			effect: resolvedEffect,
			rule,
			source,
			taskId: legacy.ctx?.taskId || null,
			sessionId: legacy.ctx?.sessionId || null,
			details,
		}),
	};
}
