// GENERATED by scripts/sync-workspace-cli.mjs — edit lib/protocol/ instead.
import {
	GOVERNANCE_DECISION_EFFECTS,
	makeGovernanceDecision,
} from "../adapters/shared/concurrency/governance-decision.mjs";

export const HELI_DECISION_EFFECTS = GOVERNANCE_DECISION_EFFECTS;

export const HELI_DECISION_CODES = Object.freeze([
	"ALLOW",
	"CONCURRENT_BOOTSTRAP",
	"LEASE_RENEWAL_REQUIRED",
	"WORKTREE_WRITER_HELD",
	"NO_SESSION",
	"UNBOUND_SESSION",
	"NOT_WRITE_MODE",
	"SESSION_INACTIVE",
	"PARENT_SESSION_INACTIVE",
	"ANCESTOR_DELEGATION_INACTIVE",
	"MALFORMED_LEASE",
	"STALE_LEASE",
	"LEASE_HELD",
	"NO_LEASE",
	"TIER_BLOCKED",
	"TIER_APPROVAL_REQUIRED",
	"ENV_WRITE_DENIED",
	"REMOTE_PUSH_DENIED",
	"TASK_GATE_DENIED",
	"PLAN_GATE_DENIED",
	"DIAGNOSIS_STATE_INVALID",
	"DIAGNOSIS_REROUTE_REQUIRED",
	"EXPENSIVE_RETRY_DENIED",
	"HUMAN_APPROVAL_REQUIRED",
	"GOVERNANCE_DENIED",
]);

export function makeDecision(options = {}) {
	return makeGovernanceDecision(options);
}

export function withStructuredDecision(result, {
	decisionId = null,
	code = null,
	effect = null,
	rule = null,
	source = "heli",
	host = null,
	toolName = null,
	reason = null,
	coverage = null,
	at = null,
	details = null,
} = {}) {
	const legacy = result && typeof result === "object" ? result : {};
	const resolvedCode = code || legacy.code || (legacy.deny ? "GOVERNANCE_DENIED" : "ALLOW");
	const resolvedEffect = effect || (legacy.deny ? "deny" : "allow");
	return {
		...legacy,
		decision: makeGovernanceDecision({
			decisionId,
			code: resolvedCode,
			effect: resolvedEffect,
			rule,
			source,
			host,
			taskId: legacy.ctx?.taskId || null,
			sessionId: legacy.ctx?.sessionId || null,
			toolName,
			reason: reason || legacy.reason || null,
			coverage: coverage || legacy.coverage || null,
			at,
			details,
		}),
	};
}
