// GENERATED by scripts/sync-workspace-cli.mjs — edit lib/protocol/ instead.
export const HELI_EVENT_SCHEMA_VERSION = 2;

export function normalizeEvent(event) {
	if (!event || typeof event !== "object" || Array.isArray(event)) return null;
	return {
		...event,
		eventSchemaVersion: Number(event.eventSchemaVersion || 1),
	};
}

export function parseEventJsonl(text) {
	const events = [];
	const warnings = [];
	for (const [index, raw] of String(text || "").split(/\r?\n/).entries()) {
		const line = raw.trim();
		if (!line) continue;
		try {
			const event = normalizeEvent(JSON.parse(line));
			if (event) events.push(event);
			else warnings.push({ line: index + 1, code: "INVALID_EVENT_RECORD" });
		} catch (error) {
			warnings.push({ line: index + 1, code: "MALFORMED_EVENT_JSON", message: error.message });
		}
	}
	return { events, warnings };
}

export function latestEvent(events, predicate = () => true) {
	for (let i = (events || []).length - 1; i >= 0; i -= 1) {
		if (predicate(events[i])) return events[i];
	}
	return null;
}
