#!/usr/bin/env node
// GENERATED by scripts/sync-workspace-cli.mjs — edit bin/heli.mjs + lib/cli/ instead.

import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { runInstall } from "./cli/install.mjs";
import { runUpdate } from "./cli/update.mjs";
import { runUninstall } from "./cli/uninstall.mjs";
import { runTarget } from "./cli/target.mjs";
import { runStatus } from "./cli/status.mjs";
import { runYolo } from "./cli/yolo.mjs";
import { runTask } from "./cli/task.mjs";
import { runSession } from "./cli/session-cmd.mjs";
import { runConflicts } from "./cli/conflicts-cmd.mjs";

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const [command, ...args] = process.argv.slice(2);

function usage() {
	console.error(`Usage: heli <command> [args]

Commands:
  install | update | uninstall
  target | status | yolo
  task create|list|show|migrate-legacy|claim|release|takeover
  session start|attach|status|list|close
  conflicts [--task id]

  heli yolo on|off|status [path] [--hours N]
`);
	process.exit(1);
}

if (!command) usage();

try {
	switch (command) {
		case "install":
			runInstall(packageRoot, args);
			break;
		case "update":
			runUpdate(packageRoot, args);
			break;
		case "uninstall":
			runUninstall(args);
			break;
		case "target":
			runTarget(args);
			break;
		case "status":
			runStatus(args);
			break;
		case "yolo":
			runYolo(args);
			break;
		case "task":
			runTask(args);
			break;
		case "session":
			runSession(args);
			break;
		case "conflicts":
			runConflicts(args);
			break;
		default:
			usage();
	}
} catch (error) {
	console.error(`Error: ${error.message}`);
	if (error.code) console.error(`Code: ${error.code}`);
	process.exit(1);
}
