// GENERATED by scripts/sync-workspace-cli.mjs — edit bin/heli.mjs + lib/cli/ instead.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join, normalize, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const PROJECT_BINDING_SCHEMA_VERSION = 1;
export const HELI_LOCK_SCHEMA_VERSION = 1;

function fail(code, message) {
	const error = new Error(message);
	error.code = code;
	throw error;
}

function plainObject(value) {
	return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function nonEmptyString(value) {
	return typeof value === "string" && value.trim().length > 0;
}

function assertRelativeResourcePath(resourceName, value) {
	if (!nonEmptyString(value)) fail("INVALID_PROJECT_RESOURCE", `resource ${resourceName} must be a non-empty relative path`);
	if (isAbsolute(value)) fail("ABSOLUTE_PROJECT_RESOURCE", `resource ${resourceName} must not contain an absolute machine path`);
	const normalized = normalize(value);
	if (normalized === ".." || normalized.startsWith(`..${process.platform === "win32" ? "\\" : "/"}`)) {
		fail("PROJECT_RESOURCE_ESCAPE", `resource ${resourceName} escapes the project root`);
	}
	return normalized;
}

export function validateWorkspaceManifest(manifest) {
	if (!plainObject(manifest)) fail("INVALID_WORKSPACE_MANIFEST", "workspace manifest must be an object");
	if (manifest.schemaVersion !== PROJECT_BINDING_SCHEMA_VERSION) fail("UNSUPPORTED_WORKSPACE_SCHEMA", `unsupported workspace schema: ${manifest.schemaVersion}`);
	if (!nonEmptyString(manifest.workspaceId)) fail("INVALID_WORKSPACE_ID", "workspaceId must be a non-empty string");
	if (!plainObject(manifest.resources) || Object.keys(manifest.resources).length === 0) fail("INVALID_PROJECT_RESOURCES", "workspace manifest must declare at least one resource");

	const resources = {};
	for (const [name, value] of Object.entries(manifest.resources)) {
		if (!nonEmptyString(name)) fail("INVALID_RESOURCE_NAME", "resource names must be non-empty strings");
		resources[name] = assertRelativeResourcePath(name, value);
	}

	for (const forbidden of ["sessions", "leases", "grants", "runtimeCapabilities", "credentials", "processHandles", "activeTask", "activeTarget"]) {
		if (Object.hasOwn(manifest, forbidden)) fail("MUTABLE_AUTHORITY_IN_PROJECT_BINDING", `${forbidden} is operational authority and must not be committed in workspace.json`);
	}

	return {
		schemaVersion: PROJECT_BINDING_SCHEMA_VERSION,
		workspaceId: manifest.workspaceId.trim(),
		resources,
		policyProfile: nonEmptyString(manifest.policyProfile) ? manifest.policyProfile.trim() : null,
	};
}

export function validateHeliLock(lock) {
	if (!plainObject(lock)) fail("INVALID_HELI_LOCK", "heli.lock must be an object");
	if (lock.schemaVersion !== HELI_LOCK_SCHEMA_VERSION) fail("UNSUPPORTED_HELI_LOCK_SCHEMA", `unsupported heli.lock schema: ${lock.schemaVersion}`);
	for (const forbidden of ["credentials", "secrets", "sessions", "leases", "grants", "runtimeCapabilities"]) {
		if (Object.hasOwn(lock, forbidden)) fail("MUTABLE_AUTHORITY_IN_HELI_LOCK", `${forbidden} must not be stored in heli.lock`);
	}
	const pins = plainObject(lock.pins) ? { ...lock.pins } : {};
	if (Object.keys(pins).length === 0) fail("EMPTY_HELI_LOCK", "heli.lock must pin at least one reproducibility input");
	for (const [name, value] of Object.entries(pins)) {
		if (!nonEmptyString(name) || !nonEmptyString(value)) fail("INVALID_HELI_LOCK_PIN", "heli.lock pins must use non-empty string keys and values");
	}
	return { schemaVersion: HELI_LOCK_SCHEMA_VERSION, pins };
}

export function resolveProjectBinding(projectRoot, manifest, lock) {
	const root = resolve(projectRoot);
	const workspace = validateWorkspaceManifest(manifest);
	const runtimeLock = validateHeliLock(lock);
	const resources = Object.fromEntries(Object.entries(workspace.resources).map(([name, relativePath]) => [name, resolve(root, relativePath)]));
	return {
		projectRoot: root,
		workspace,
		lock: runtimeLock,
		resources,
		// This object is identity/reproducibility data only. It deliberately carries no live authority.
		authority: null,
	};
}

export function writeProjectBinding(projectRoot, manifest, lock, { heliDir = ".heli", overwrite = false } = {}) {
	const root = resolve(projectRoot);
	const workspace = validateWorkspaceManifest(manifest);
	const runtimeLock = validateHeliLock(lock);
	const bindingDir = join(root, heliDir);
	const workspacePath = join(bindingDir, "workspace.json");
	const lockPath = join(bindingDir, "heli.lock");

	if (!overwrite && (existsSync(workspacePath) || existsSync(lockPath))) {
		fail("PROJECT_BINDING_EXISTS", `project binding already exists under ${bindingDir}`);
	}

	mkdirSync(bindingDir, { recursive: true });
	writeFileSync(workspacePath, `${JSON.stringify(workspace, null, 2)}\n`, "utf8");
	writeFileSync(lockPath, `${JSON.stringify(runtimeLock, null, 2)}\n`, "utf8");
	return resolveProjectBinding(root, workspace, runtimeLock);
}

export function readProjectBinding(projectRoot, { heliDir = ".heli" } = {}) {
	const root = resolve(projectRoot);
	const workspacePath = join(root, heliDir, "workspace.json");
	const lockPath = join(root, heliDir, "heli.lock");
	const manifest = JSON.parse(readFileSync(workspacePath, "utf8"));
	const lock = JSON.parse(readFileSync(lockPath, "utf8"));
	return resolveProjectBinding(root, manifest, lock);
}

export function projectRootFromModule(moduleUrl) {
	return dirname(fileURLToPath(moduleUrl));
}
