// GENERATED by scripts/sync-workspace-cli.mjs — edit bin/heli.mjs + lib/cli/ instead.
import { existsSync, readFileSync } from "node:fs";
import { findWorkspaceRoot } from "../adapters/shared/concurrency/paths.mjs";
import {
	authorizeAction,
	classifyHypothesis,
	establishRootCause,
	recordCheckpoint,
	recordDecision,
	recordEvidence,
	recordRun,
	readDiagnosis,
	routeDiagnosis,
	setHypothesis,
	startDiagnosis,
} from "../adapters/shared/concurrency/diagnosis.mjs";

function requireWorkspace(cwd) {
	const root = findWorkspaceRoot(cwd);
	if (!root) throw new Error(`No Heli workspace found from ${cwd}`);
	return root;
}

function parseArgs(args) {
	const flags = {};
	const positional = [];
	for (let i = 0; i < args.length; i += 1) {
		const item = args[i];
		if (item === "--json" && args[i + 1]) flags.json = args[++i];
		else if (item === "--type" && args[i + 1]) flags.type = args[++i];
		else if (item === "--route" && args[i + 1]) flags.route = args[++i];
		else if (item === "--session" && args[i + 1]) flags.sessionId = args[++i];
		else if (item === "--reason" && args[i + 1]) flags.reason = args[++i];
		else if (item.startsWith("--")) flags[item.slice(2)] = true;
		else positional.push(item);
	}
	return { flags, positional };
}

function payloadFrom(flags) {
	if (!flags.json) return {};
	try {
		const value = JSON.parse(flags.json);
		if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("payload must be a JSON object");
		return value;
	} catch (error) {
		const err = new Error(`invalid --json payload: ${error.message}`);
		err.code = "INVALID_JSON_PAYLOAD";
		throw err;
	}
}

function usage() {
	console.log(`Usage:
  heli diagnosis show <task-id> [path]
  heli diagnosis init <task-id> --json <object> [path]
  heli diagnosis record <task-id> --type <failure|evidence|hypothesis|classify|root-cause|checkpoint|decision|run> --json <object> [path]
  heli diagnosis route <task-id> --route <verify-premise|debug|fix-loop|impact|incident> [--reason text] [path]
  heli diagnosis gate <task-id> --json <action-object> [path]`);
}

export function runDiagnosis(args) {
	const [sub, ...rest] = args;
	const { flags, positional } = parseArgs(rest);
	if (!sub || !["show", "init", "record", "route", "gate"].includes(sub)) {
		usage();
		return;
	}
	const taskId = positional[0];
	if (!taskId) {
		usage();
		return;
	}
	const cwd = positional[1] || process.cwd();
	const workspaceRoot = requireWorkspace(cwd);
	const sessionId = flags.sessionId || process.env.HELI_SESSION_ID || null;

	if (sub === "show") {
		console.log(JSON.stringify(readDiagnosis(workspaceRoot, taskId), null, 2));
		return;
	}

	let result;
	if (sub === "init") {
		result = startDiagnosis(workspaceRoot, taskId, payloadFrom(flags), { sessionId });
	} else if (sub === "route") {
		result = routeDiagnosis(workspaceRoot, taskId, { ...payloadFrom(flags), route: flags.route, reason: flags.reason }, { sessionId });
	} else if (sub === "gate") {
		result = authorizeAction(workspaceRoot, taskId, payloadFrom(flags), { sessionId });
		console.log(JSON.stringify({ allowed: result.allowed, code: result.code, reason: result.reason || null, review: result.review || null }, null, 2));
		if (!result.allowed) process.exitCode = 2;
		return;
	} else {
		const type = String(flags.type || "").toLowerCase();
		const payload = payloadFrom(flags);
		const options = { sessionId };
		switch (type) {
			case "failure":
			case "run":
				result = recordRun(workspaceRoot, taskId, type === "failure" ? { ...payload, status: payload.status || "failed" } : payload, options);
				break;
			case "evidence":
				result = recordEvidence(workspaceRoot, taskId, payload, options);
				break;
			case "hypothesis":
				result = setHypothesis(workspaceRoot, taskId, payload, options);
				break;
			case "classify":
				result = classifyHypothesis(workspaceRoot, taskId, payload, options);
				break;
			case "root-cause":
			case "root_cause":
				result = establishRootCause(workspaceRoot, taskId, payload, options);
				break;
			case "checkpoint":
				result = recordCheckpoint(workspaceRoot, taskId, payload, options);
				break;
			case "decision":
				result = recordDecision(workspaceRoot, taskId, payload, options);
				break;
			default: {
				const error = new Error("record requires --type and a supported transition");
				error.code = "INVALID_DIAGNOSIS_TRANSITION";
				throw error;
			}
		}
	}
	console.log(JSON.stringify(result, null, 2));
}
