// GENERATED by scripts/sync-workspace-cli.mjs — edit bin/heli.mjs + lib/cli/ instead.
/**
 * heli doctor [path] — offline workspace health report.
 *
 * Strictly local: reads files under .heli-harness/ and the paths they point at.
 * Never opens a socket, never shells out, never mutates workspace state — so it
 * is safe to run mid-task, on a plane, or against a half-broken install.
 *
 * Exit code is 1 only when a check FAILs. Warnings are advisory and exit 0, so
 * `heli doctor` can be wired into a shell prompt or CI smoke without flapping.
 */
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { isAbsolute, join, resolve } from "node:path";
import { findWorkspaceRoot } from "../adapters/shared/concurrency/paths.mjs";
import { readWorkspaceSchema } from "../adapters/shared/concurrency/schema.mjs";
import { listTasks, listActiveTasks } from "../adapters/shared/concurrency/task.mjs";
import { readLease, isLeaseExpired } from "../adapters/shared/concurrency/lease.mjs";
import { listSessions, listActiveSessions, readSession } from "../adapters/shared/concurrency/session.mjs";
import { listAllBindings } from "../adapters/shared/concurrency/binding.mjs";

const ICON = { ok: "✅", warn: "⚠️", fail: "❌" };
const TAG = { ok: "ok  ", warn: "WARN", fail: "FAIL" };

/** Read JSON, distinguishing "absent" from "present but unparseable". */
function loadJson(path) {
	if (!existsSync(path)) return { present: false, data: null };
	try {
		return { present: true, data: JSON.parse(readFileSync(path, "utf8")) };
	} catch (error) {
		return { present: true, data: null, error };
	}
}

function resolveRepoPath(workspaceRoot, p) {
	if (!p) return "";
	return isAbsolute(p) ? p : resolve(workspaceRoot, p);
}

export function runDoctor(args) {
	const cwd = (args || []).find((a) => a && !a.startsWith("--")) || process.cwd();
	const counts = { ok: 0, warn: 0, fail: 0 };

	const report = (level, line) => {
		counts[level] += 1;
		console.log(`${ICON[level]} ${TAG[level]}  ${line}`);
	};
	// Advisory context — deliberately uncounted so honesty notes never inflate
	// the ok/warn/fail tally.
	const info = (line) => console.log(`         ${line}`);
	const summary = () => {
		console.log("");
		console.log(`doctor: ${counts.ok} ok, ${counts.warn} warnings, ${counts.fail} failures`);
		if (counts.fail > 0) process.exitCode = 1;
	};

	// ---------------------------------------------------------------- workspace
	const workspaceRoot = findWorkspaceRoot(cwd) || (existsSync(join(cwd, ".heli-harness")) ? cwd : null);
	if (!workspaceRoot) {
		console.log(`Heli doctor — ${cwd}`);
		console.log("");
		report("fail", `no Heli workspace found at or above ${cwd} — run: npx github:KJ-AIML/heli-harness install .`);
		summary();
		return;
	}
	const harness = join(workspaceRoot, ".heli-harness");
	console.log(`Heli doctor — ${workspaceRoot}`);
	console.log("");
	report("ok", `workspace root: ${workspaceRoot}`);

	const manifest = loadJson(join(harness, "manifest.json"));
	if (!manifest.present) {
		report("fail", "manifest.json missing — run: npx github:KJ-AIML/heli-harness update .");
	} else if (!manifest.data) {
		report("fail", "manifest.json unparseable — run: npx github:KJ-AIML/heli-harness update .");
	} else {
		report("ok", `manifest version: ${manifest.data.version || "unknown"}`);
	}

	// ------------------------------------------------------------------- schema
	const schema = readWorkspaceSchema(workspaceRoot);
	if (!schema.exists) {
		report("warn", "workspace/schema.json missing — treated as legacy mode (no lease enforcement)");
	} else if (schema.malformed) {
		report(
			"fail",
			"workspace/schema.json malformed — enforcement fails closed to concurrent; repair or rewrite it (heli task create re-seeds mode)",
		);
	} else {
		report("ok", `workspace mode: ${schema.mode}`);
	}
	const concurrent = schema.mode === "concurrent";

	// -------------------------------------------------------------------- index
	const index = loadJson(join(harness, "workspace", "index.json"));
	let repos = [];
	if (!index.present) {
		report("warn", "workspace/index.json missing — no repos registered");
	} else if (!index.data) {
		report("fail", "workspace/index.json unparseable — target resolution and repo checks cannot run");
	} else if (!Array.isArray(index.data.repos)) {
		report("warn", "workspace/index.json has no repos array — no repos registered");
	} else {
		repos = index.data.repos;
		report("ok", `registered repos: ${repos.length}`);
		const missing = repos.filter((r) => !existsSync(resolveRepoPath(workspaceRoot, r?.path)));
		if (missing.length) {
			report(
				"warn",
				`registered repo path missing on disk: ${missing.map((r) => `${r?.name || "?"} -> ${r?.path || "(no path)"}`).join(", ")}`,
			);
		}
	}

	// ------------------------------------------------------------------- target
	const target = loadJson(join(harness, "workspace", "target.json"));
	if (target.present && !target.data) {
		report("fail", "workspace/target.json unparseable — target discipline cannot be enforced");
	} else {
		const targetRepo = target.data?.targetRepo || "";
		if (!targetRepo) {
			report("warn", "no target selected — run: heli target set <repo>");
		} else {
			const entry = repos.find((r) => r?.name === targetRepo);
			if (!entry) {
				report("warn", `target "${targetRepo}" is not in workspace/index.json — run: heli target list`);
			}
			const targetPath = resolveRepoPath(workspaceRoot, entry?.path || target.data?.targetGitRoot || "");
			if (!targetPath) {
				report("warn", `target "${targetRepo}" has no resolvable path (no index entry, no targetGitRoot)`);
			} else if (!existsSync(targetPath)) {
				report("fail", `target "${targetRepo}" path missing on disk: ${targetPath}`);
			} else {
				report("ok", `target repo: ${targetRepo} (${targetPath})`);
			}
		}
	}

	// -------------------------------------------------------------------- tasks
	const tasks = listTasks(workspaceRoot);
	const byStatus = new Map();
	for (const t of tasks) {
		const s = String(t.status || "unknown");
		byStatus.set(s, (byStatus.get(s) || 0) + 1);
	}
	const statusLine = tasks.length
		? [...byStatus.entries()].map(([s, n]) => `${s}=${n}`).join(" ")
		: "none";
	report("ok", `tasks: ${tasks.length} (${statusLine})`);
	if (!concurrent) {
		info("legacy mode: shared state/current-task.md is authoritative; leases are not enforced");
	}

	for (const task of listActiveTasks(workspaceRoot)) {
		const lease = readLease(workspaceRoot, task.taskId);
		if (!lease) {
			report("ok", `task ${task.taskId}: no write lease (unclaimed)`);
			continue;
		}
		if (lease.invalid) {
			report("warn", `task ${task.taskId}: malformed lease — ${lease.reason} (inspect ${lease.path})`);
			continue;
		}
		if (isLeaseExpired(lease)) {
			report(
				"warn",
				`task ${task.taskId}: write lease expired ${lease.expiresAt} (owner ${lease.sessionId}) — own session self-renews on claim; another session needs: heli task takeover ${task.taskId} --confirm`,
			);
		} else {
			report("ok", `task ${task.taskId}: active write lease (owner ${lease.sessionId}, expires ${lease.expiresAt})`);
		}
		if (!readSession(workspaceRoot, lease.sessionId)) {
			report(
				"warn",
				`task ${task.taskId}: orphan lease — session record ${lease.sessionId} not found under sessions/`,
			);
		}
	}

	// ------------------------------------------------------- sessions / bindings
	const sessions = listSessions(workspaceRoot);
	report("ok", `sessions: ${sessions.length} (${listActiveSessions(workspaceRoot).length} active)`);

	const bindings = listAllBindings(workspaceRoot);
	report("ok", `worktree bindings: ${bindings.length}`);
	for (const b of bindings) {
		const p = b?.canonicalWorktreePath || "";
		if (p && !existsSync(p)) {
			report("warn", `binding worktree missing on disk: ${p}${b.taskId ? ` (task ${b.taskId})` : ""}`);
		}
	}

	// ------------------------------------------------------------- embedded CLI
	if (existsSync(join(harness, "heli.mjs")) && existsSync(join(harness, "cli"))) {
		report("ok", "embedded CLI present: node .heli-harness/heli.mjs <cmd> works offline");
	} else {
		report("fail", "embedded CLI missing (.heli-harness/heli.mjs + cli/) — run: npx github:KJ-AIML/heli-harness update .");
	}

	// ------------------------------------------------------------- host plugins
	if (existsSync(join(harness, "adapters"))) {
		report("ok", "host adapter/plugin files present under .heli-harness/adapters");
	} else {
		report("warn", ".heli-harness/adapters missing — run: npx github:KJ-AIML/heli-harness update .");
	}
	info(
		"host plugin activation: not verifiable from files — plugin PreToolUse is live only when the host loaded the Heli plugin this session (SessionStart marker). File/pointer installs without the plugin are advisory.",
	);

	// -------------------------------------------------------------- cloud sync
	const sync = loadJson(join(harness, "state", "sync.json"));
	if (!sync.present) {
		report("ok", "cloud sync: local-only (default)");
	} else if (!sync.data) {
		report("warn", "state/sync.json unparseable — cloud link state unknown; heli push/pull will refuse");
	} else {
		report(
			"ok",
			`cloud sync: linked to "${sync.data.name || sync.data.workspaceId || "unknown"}" lastVersion=${sync.data.lastVersion ?? 0} auto=${sync.data.auto ? "on" : "off"} e2e=${sync.data.e2e ? "on" : "off"}`,
		);
		const credentials = join(process.env.HELI_CONFIG_DIR || join(homedir(), ".heli"), "credentials.json");
		if (!existsSync(credentials)) {
			report("warn", `linked but not logged in on this machine (${credentials} missing) — run: heli auth login`);
		}
	}

	// -------------------------------------------------------------------- yolo
	const yolo = loadJson(join(harness, "state", "yolo.json"));
	if (!yolo.present) {
		report("ok", "yolo: off (strict guards)");
	} else if (!yolo.data) {
		report("warn", "state/yolo.json unparseable — guard state ambiguous; run: heli yolo off");
	} else {
		const expiresAt = yolo.data.expiresAt || "";
		const expired = expiresAt && !Number.isNaN(Date.parse(expiresAt)) && Date.now() > Date.parse(expiresAt);
		const detail = [
			yolo.data.scope ? `scope=${yolo.data.scope}` : "",
			expiresAt ? `expires=${expiresAt}` : "no expiry",
			yolo.data.enabledBy ? `by=${yolo.data.enabledBy}` : "",
		]
			.filter(Boolean)
			.join(" ");
		if (yolo.data.enabled === true && !expired) {
			report("warn", `yolo active — PreToolUse skips git-push/.env/stuck-task gates (${detail}); run: heli yolo off`);
		} else {
			report("warn", `stale state/yolo.json present (${expired ? "expired" : "disabled"}: ${detail}) — run: heli yolo off`);
		}
	}
	info("yolo env vars (HELI_YOLO / HELI_GUARDS) are per-shell and not visible here — check: heli yolo status");

	summary();
}
