// GENERATED by scripts/sync-workspace-cli.mjs — edit bin/heli.mjs + lib/cli/ instead.
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { findWorkspaceRoot } from "../adapters/shared/concurrency/paths.mjs";
import { resolveExecutionContext, evaluateOwnershipGate } from "../adapters/shared/concurrency/resolve.mjs";
import { readTask, listActiveTasks } from "../adapters/shared/concurrency/task.mjs";
import { readLease, isLeaseExpired } from "../adapters/shared/concurrency/lease.mjs";
import { taskPaths } from "../adapters/shared/concurrency/paths.mjs";
import { parseEventJsonl, latestEvent } from "../protocol/events.mjs";
import { protocolOk, protocolError } from "../protocol/result.mjs";
import { wantsJson, stripOutputFlags, printProtocolResult } from "./output.mjs";

function readJson(path, fallback = null) {
	try {
		return JSON.parse(readFileSync(path, "utf8"));
	} catch {
		return fallback;
	}
}

function argsForExplain(args) {
	const json = wantsJson(args);
	const clean = stripOutputFlags(args);
	const subject = clean[0] || "authority";
	let taskId = null;
	const positional = [];
	for (let i = 1; i < clean.length; i += 1) {
		if (clean[i] === "--task" && clean[i + 1]) taskId = clean[++i];
		else if (!clean[i].startsWith("--")) positional.push(clean[i]);
	}
	return { json, subject, taskId, cwd: positional[0] || process.cwd() };
}

function authorityExplanation(ctx) {
	const lease = ctx.taskId ? readLease(ctx.workspaceRoot, ctx.taskId) : null;
	const activeLease = lease && !lease.invalid && !isLeaseExpired(lease) ? lease : null;
	const gate = evaluateOwnershipGate(ctx, { isWrite: true });
	const writable = !gate.deny;
	const reasons = [];
	if (gate.reason) reasons.push(gate.reason);
	else if (gate.bootstrap) reasons.push("concurrent bootstrap write is allowed because no task exists yet");
	else if (gate.renewalRequired) reasons.push("write is allowed subject to renewing the expired own lease before execution");
	else reasons.push("canonical ownership evaluator allows the write");
	return {
		workspaceRoot: ctx.workspaceRoot,
		workspaceMode: ctx.concurrentMode ? "concurrent" : "legacy",
		sessionId: ctx.sessionId || null,
		taskId: ctx.taskId || null,
		mode: ctx.mode || null,
		target: ctx.target?.targetRepo || null,
		worktree: ctx.worktreeRoot || null,
		lease: lease ? { owner: lease.sessionId || null, expiresAt: lease.expiresAt || null, active: Boolean(activeLease), invalid: Boolean(lease.invalid) } : null,
		writable,
		decisionCode: gate.code || (writable ? "ALLOW" : "DENY"),
		bootstrap: Boolean(gate.bootstrap),
		renewalRequired: Boolean(gate.renewalRequired),
		reasons,
	};
}

function explainCapabilities(workspaceRoot, ctx) {
	const manifest = readJson(join(workspaceRoot, ".heli-harness", "adapters", "adapters.json"), { adapters: [] });
	const adapters = Array.isArray(manifest?.adapters) ? manifest.adapters : [];
	const selected = adapters.find((adapter) => adapter.id === ctx.host) || null;
	return {
		host: ctx.host || "unknown",
		selectedAdapter: selected ? {
			id: selected.id,
			status: selected.status,
			capabilities: selected.capabilities || {},
		} : null,
		adapters: adapters.map((adapter) => ({
			id: adapter.id,
			status: adapter.status,
			capabilities: adapter.capabilities || {},
		})),
		note: "declared package metadata is not proof that a host loaded the adapter in this session",
	};
}

function explainGuard(workspaceRoot, taskId) {
	if (!taskId) return { taskId: null, latestDecision: null, warnings: ["no task is bound; pass --task <id>"] };
	const path = taskPaths(workspaceRoot, taskId).eventsJsonl;
	if (!existsSync(path)) return { taskId, latestDecision: null, warnings: ["task event stream does not exist"] };
	const parsed = parseEventJsonl(readFileSync(path, "utf8"));
	const event = latestEvent(parsed.events, (item) => item.type === "guard.decision" || item.type === "guard_decision");
	return { taskId, latestDecision: event, warnings: parsed.warnings };
}

export function runExplain(args = []) {
	const { json, subject, taskId: explicitTaskId, cwd } = argsForExplain(args);
	const workspaceRoot = findWorkspaceRoot(cwd);
	if (!workspaceRoot) {
		const result = protocolError(`explain.${subject}`, "WORKSPACE_NOT_FOUND", `No Heli workspace found from ${cwd}`);
		if (json) printProtocolResult(result);
		else console.log(result.errors[0].message);
		process.exitCode = 1;
		return result;
	}
	const ctx = resolveExecutionContext({ cwd, host: "cli", createIfMissing: false, refreshLeaseOnResolve: false });
	let data;
	if (subject === "authority") data = authorityExplanation(ctx);
	else if (subject === "task") {
		const taskId = explicitTaskId || ctx.taskId || listActiveTasks(workspaceRoot)[0]?.taskId || null;
		data = { taskId, task: taskId ? readTask(workspaceRoot, taskId) : null };
	} else if (subject === "capabilities") data = explainCapabilities(workspaceRoot, ctx);
	else if (subject === "guard") data = explainGuard(workspaceRoot, explicitTaskId || ctx.taskId || null);
	else {
		const result = protocolError(`explain.${subject}`, "UNKNOWN_EXPLAIN_SUBJECT", `Unknown explain subject: ${subject}`);
		if (json) printProtocolResult(result);
		else console.log(result.errors[0].message);
		process.exitCode = 1;
		return result;
	}
	const result = protocolOk(`explain.${subject}`, data, { warnings: data?.warnings || [] });
	if (json) printProtocolResult(result);
	else if (subject === "authority") {
		console.log(`Workspace: ${data.workspaceRoot}`);
		console.log(`Task: ${data.taskId || "unbound"}`);
		console.log(`Session: ${data.sessionId || "none"}`);
		console.log(`Mode: ${data.mode || "n/a"}`);
		console.log(`Target: ${data.target || "n/a"}`);
		console.log(`Effective write authority: ${data.writable ? "allowed" : "denied"}`);
		for (const reason of data.reasons) console.log(`- ${reason}`);
	} else console.log(JSON.stringify(data, null, 2));
	return result;
}
