// GENERATED by scripts/sync-workspace-cli.mjs — edit bin/heli.mjs + lib/cli/ instead.
/**
 * heli governance show|set — workspace governance profile.
 *
 * flow is the default. strict keeps the older fail-closed writer gate.
 * observe records conflicts and does not block ordinary development writes.
 */
import { findWorkspaceRoot } from "../adapters/shared/concurrency/paths.mjs";
import {
	DEFAULT_GOVERNANCE_PROFILE,
	GOVERNANCE_PROFILES,
	ensureGovernanceProfile,
	readGovernanceProfile,
	setGovernanceProfile,
} from "../adapters/shared/concurrency/flow-governance.mjs";
import { protocolOk } from "../protocol/result.mjs";
import { printProtocolResult, stripOutputFlags, wantsJson } from "./output.mjs";

function workspaceFrom(args) {
	const positional = (args || []).filter((value) => value && !value.startsWith("--"));
	return positional[0] || process.cwd();
}

function requireWorkspace(cwd) {
	const workspaceRoot = findWorkspaceRoot(cwd);
	if (!workspaceRoot) {
		throw Object.assign(new Error(`No Heli workspace found from ${cwd}`), { code: "WORKSPACE_NOT_FOUND" });
	}
	return workspaceRoot;
}

export function runGovernance(args) {
	const json = wantsJson(args || []);
	const clean = stripOutputFlags(args || []);
	const [sub, ...rest] = clean;
	if (sub === "set") {
		const profile = rest.find((value) => GOVERNANCE_PROFILES.includes(value));
		if (!profile) {
			throw Object.assign(
				new Error(`Usage: heli governance set <${GOVERNANCE_PROFILES.join("|")}> [path]`),
				{ code: "INVALID_GOVERNANCE_PROFILE" },
			);
		}
		const workspaceRoot = requireWorkspace(rest.find((value) => value !== profile) || process.cwd());
		const record = setGovernanceProfile(workspaceRoot, profile);
		const data = { workspaceRoot, profile: record.profile, record };
		if (json) printProtocolResult(protocolOk("governance.set", data));
		else console.log(`Governance profile: ${record.profile}`);
		return;
	}
	if (sub === "show" || !sub) {
		const workspaceRoot = requireWorkspace(workspaceFrom(rest));
		const record = ensureGovernanceProfile(workspaceRoot);
		const profile = readGovernanceProfile(workspaceRoot);
		const data = { workspaceRoot, profile, defaultProfile: DEFAULT_GOVERNANCE_PROFILE, record };
		if (json) printProtocolResult(protocolOk("governance.show", data));
		else {
			console.log(`Governance profile: ${profile}`);
			console.log(`Workspace: ${workspaceRoot}`);
			if (record?.migratedFrom) console.log(`Migrated from: ${record.migratedFrom}`);
		}
		return;
	}
	throw Object.assign(new Error("Usage: heli governance <show|set> [flow|strict|observe] [path]"), {
		code: "USAGE",
	});
}
