// GENERATED by scripts/sync-workspace-cli.mjs — edit bin/heli.mjs + lib/cli/ instead.
import { findWorkspaceRoot, resolveWorktreeRoot } from "../adapters/shared/concurrency/paths.mjs";
import { resourceIdForWorktree } from "../adapters/shared/concurrency/resource-authority.mjs";
import {
	issueGrant,
	listGrants,
	revokeGrant,
} from "../adapters/shared/concurrency/grant.mjs";
import { projectWorkspaceKey } from "../adapters/shared/concurrency/project-binding.mjs";
import { wantsJson, stripOutputFlags, printProtocolResult } from "./output.mjs";
import { protocolOk } from "../protocol/result.mjs";

function error(code, message) {
	const value = new Error(message);
	value.code = code;
	return value;
}

function parse(args) {
	const json = wantsJson(args);
	const clean = stripOutputFlags(args);
	const sub = clean[0] || "list";
	const flags = {};
	const positional = [];
	for (let i = 1; i < clean.length; i += 1) {
		const value = clean[i];
		if (["--action", "--scope", "--session", "--resource", "--minutes", "--reason"].includes(value) && clean[i + 1]) {
			flags[value.slice(2)] = clean[++i];
		} else if (value === "--all") flags.all = true;
		else if (!value.startsWith("--")) positional.push(value);
	}
	return { json, sub, flags, positional };
}

function workspaceFrom(positional) {
	const candidate = positional[1] || positional[0] || process.cwd();
	const root = findWorkspaceRoot(candidate);
	if (!root) throw error("WORKSPACE_NOT_FOUND", `No Heli workspace found from ${candidate}`);
	return root;
}

function resourceFor(workspaceRoot, flag) {
	if (flag === "workspace") {
		return { type: "workspace", id: projectWorkspaceKey(workspaceRoot) };
	}
	const worktree = resolveWorktreeRoot(workspaceRoot);
	return { type: "worktree", id: flag || resourceIdForWorktree(worktree) };
}

export function runGrant(args = []) {
	const { json, sub, flags, positional } = parse(args);
	let result;
	if (sub === "issue") {
		const workspaceRoot = workspaceFrom(positional);
		if (!flags.action) throw error("GRANT_ACTION_REQUIRED", "--action is required");
		const minutes = Number(flags.minutes);
		const grant = issueGrant(workspaceRoot, {
			action: flags.action,
			scope: flags.scope || "once",
			subjectSessionId: flags.session || process.env.HELI_SESSION_ID || null,
			resource: resourceFor(workspaceRoot, flags.resource),
			ttlSeconds: Number.isFinite(minutes) && minutes > 0 ? minutes * 60 : null,
			reason: flags.reason || null,
		});
		result = { workspaceRoot, grant };
	} else if (sub === "list") {
		const workspaceRoot = workspaceFrom(positional);
		result = {
			workspaceRoot,
			grants: listGrants(workspaceRoot, { activeOnly: !flags.all }),
		};
	} else if (sub === "revoke") {
		const grantId = positional[0];
		if (!grantId) throw error("GRANT_ID_REQUIRED", "grant id required");
		const workspaceRoot = findWorkspaceRoot(positional[1] || process.cwd());
		if (!workspaceRoot) throw error("WORKSPACE_NOT_FOUND", "No Heli workspace found");
		result = { workspaceRoot, grant: revokeGrant(workspaceRoot, grantId) };
	} else {
		throw error("UNKNOWN_GRANT_COMMAND", `unknown grant command: ${sub}`);
	}

	if (json) {
		printProtocolResult(protocolOk(`grant.${sub}`, result));
		return result;
	}
	if (sub === "list") {
		if (!result.grants.length) console.log("No active scoped grants.");
		for (const grant of result.grants) {
			console.log(`${grant.grantId}  action=${grant.action} scope=${grant.scope} resource=${grant.resource.type}:${grant.resource.id} expires=${grant.expiresAt || "none"}`);
		}
	} else {
		const grant = result.grant;
		console.log(`${sub === "revoke" ? "Revoked" : "Issued"} grant ${grant.grantId}`);
		console.log(`  action: ${grant.action}`);
		console.log(`  scope: ${grant.scope}`);
		console.log(`  resource: ${grant.resource.type}:${grant.resource.id}`);
		console.log(`  execution: ${grant.executionId}`);
	}
	return result;
}
