// GENERATED by scripts/sync-workspace-cli.mjs — edit bin/heli.mjs + lib/cli/ instead.
import {
	listHandoffs,
	publishHandoff,
	readHandoff,
} from "../adapters/shared/concurrency/handoff.mjs";
import { runHandoffMachine } from "./machine.mjs";
import { findWorkspaceRoot } from "../adapters/shared/concurrency/paths.mjs";

function requireWorkspace(cwd) {
	const root = findWorkspaceRoot(cwd);
	if (!root) {
		const error = new Error(`No Heli workspace found from ${cwd}`);
		error.code = "WORKSPACE_NOT_FOUND";
		throw error;
	}
	return root;
}

function parse(args) {
	const flags = {};
	const positional = [];
	for (let i = 0; i < args.length; i += 1) {
		const value = args[i];
		if (["--task", "--name", "--ref", "--path", "--session"].includes(value) && args[i + 1]) {
			flags[value.slice(2)] = args[++i];
		} else if (value === "--json" || value === "--output-json") {
			flags.outputJson = true;
		} else if (value.startsWith("--")) {
			flags[value.slice(2)] = true;
		} else positional.push(value);
	}
	return { flags, positional };
}

export function runHandoff(args = []) {
	if (args.includes("--json") || args.includes("--output-json")) return runHandoffMachine(args);
	const [sub, ...rest] = args;
	const { flags, positional } = parse(rest);
	const cwd = positional.filter((value) => value !== "--json").at(-1) || process.cwd();
	const workspaceRoot = requireWorkspace(cwd);

	switch (sub) {
		case "publish": {
			if (!flags.task || !flags.name || !flags.ref) {
				console.log("Usage: heli handoff publish --task <producer-task> --name <artifact-name> --ref <git-ref> [--path <repo-relative-path>] [path]");
				return;
			}
			const result = publishHandoff(workspaceRoot, {
				producerTaskId: flags.task,
				artifactName: flags.name,
				ref: flags.ref,
				path: flags.path || null,
				sessionId: flags.session || process.env.HELI_SESSION_ID || null,
			});
			console.log(`${result.created ? "Published" : "Already published"} ${result.publication.producerTaskId}/${result.publication.artifactName}`);
			console.log(`  ref: ${result.publication.ref}`);
			console.log(`  path: ${result.publication.path || "(none)"}`);
			console.log(`  publishedAt: ${result.publication.publishedAt}`);
			return;
		}
		case "list": {
			const publications = listHandoffs(workspaceRoot);
			if (!publications.length) {
				console.log("No handoffs published.");
				return;
			}
			console.log(`Handoffs: ${publications.length}`);
			for (const publication of publications) {
				console.log(`- ${publication.producerTaskId}/${publication.artifactName}  ref=${publication.ref}  path=${publication.path || "(none)"}`);
			}
			return;
		}
		case "show": {
			const identity = positional.find((value) => value.includes("/"));
			if (!identity) {
				console.log("Usage: heli handoff show <producer-task>/<artifact-name> [path]");
				return;
			}
			const slash = identity.indexOf("/");
			const publication = readHandoff(workspaceRoot, identity.slice(0, slash), identity.slice(slash + 1));
			if (!publication) {
				const error = new Error(`handoff not found: ${identity}`);
				error.code = "HANDOFF_NOT_FOUND";
				throw error;
			}
			console.log(JSON.stringify(publication, null, 2));
			return;
		}
		default:
			console.log("Usage: heli handoff publish|list|show ...");
	}
}
