// GENERATED by scripts/sync-workspace-cli.mjs — edit bin/heli.mjs + lib/cli/ instead.
const HELP_FLAG_SET = new Set(["--help", "-h"]);

const TOP_LEVEL = [
	["help", "Show read-only help for Heli commands and subcommands."],
	["setup", "Initialize Heli's machine-global config/data directories."],
	["link", "Link a workspace or register a nested Git repo under its linked parent."],
	["repo", "List, register, remove, or discover Git repositories inside one Heli workspace."],
	["host", "Inspect and manage coding-host integrations."],
	["grant", "Issue, list, or revoke scoped governance grants."],
	["install", "Install an embedded Heli workspace (legacy/portable topology)."],
	["update", "Update an existing linked or embedded Heli workspace."],
	["migrate", "Migrate registered linked workspaces to the current global Heli runtime."],
	["uninstall", "Remove Heli workspace files/binding from a project."],
	["target", "Inspect or select the active repository target."],
	["status", "Show workspace, task, session, authority, and host-packaging state."],
	["resume", "Build a read-only continuation packet for switching hosts/sessions."],
	["doctor", "Run offline workspace health checks. --repair clears safe stale authority."],
	["governance", "Show or set the workspace governance profile (flow, strict, observe)."],
	["yolo", "Inspect or change the local reduced-protection YOLO switch."],
	["task", "Manage durable work records, dependencies, and compatibility claims."],
	["handoff", "Publish and inspect artifact handoffs between tasks."],
	["diagnosis", "Record and inspect structured debugging/diagnosis evidence."],
	["session", "Inspect and manage Heli session lifecycle."],
	["conflicts", "Show known task/resource conflicts."],
	["explain", "Explain authority, task, guard, capability, and policy state."],
	["trace", "Show the recorded governance event stream for a task."],
	["auth", "Manage optional cloud-sync authentication."],
	["ws", "Manage optional cloud-sync workspaces."],
	["push", "Push optional cloud-sync workspace state."],
	["pull", "Pull optional cloud-sync workspace state."],
	["sync", "Run or configure optional cloud sync."],
	["init", "Create/restore an optional cloud-sync workspace."],
];

const COMMANDS = {
	help: {
		usage: "heli help [command] [subcommand]",
		summary: "Show read-only help. Help never executes the referenced command.",
	},
	setup: {
		usage: "heli setup [--json]",
		summary: "Initialize Heli's machine-global environment. Does not link a project.",
	},
	link: {
		usage: "heli link [path] [--workspace-id <id>] [--json]",
		summary: "Link a workspace to the global Heli runtime. Inside an existing linked ancestor, registers the nested Git repo instead of creating a second workspace.",
	},
	repo: {
		usage: "heli repo <list|add|remove|discover> [options]",
		summary: "Manage the Git repository inventory of one Heli workspace without changing sessions or writer authority.",
		subcommands: {
			list: "heli repo list [workspace-or-repo-path] [--json]",
			add: "heli repo add [repo-path] [--name <id>] [--profile <profile>] [--json]",
			remove: "heli repo remove <id-or-name-or-path> [workspace-path] [--json]",
			discover: "heli repo discover [path] [--depth N] [--json]",
		},
	},
	host: {
		usage: "heli host <status|list|install|update|repair|remove> [all|host...] [--dry-run]",
		summary: "Inspect or manage host-native Heli integrations.",
		subcommands: {
			status: "heli host status",
			list: "heli host list",
			install: "heli host install [all|codex|pi|claude|grok|opencode|kimi|cursor|axga|antigravity|generic] [--dry-run]",
			update: "heli host update [all|codex|pi|claude|grok|opencode|kimi|cursor|axga|antigravity|generic] [--dry-run]",
			repair: "heli host repair [all|codex|pi|claude|grok|opencode|kimi|cursor|axga|antigravity|generic] [--dry-run]",
			remove: "heli host remove [all|codex|pi|claude|grok|opencode|kimi|cursor|axga|antigravity|generic] [--dry-run]",
		},
	},
	grant: {
		usage: "heli grant <issue|list|revoke> [options] [path]",
		summary: "Manage scoped governance grants. Grant issuance remains human-gated.",
		subcommands: {
			issue: "heli grant issue --action <action> [--scope once|session|ttl] [--session <id>] [--resource <id|workspace>] [--minutes N] [--reason <text>] [--execution <id>] [path]",
			list: "heli grant list [--all] [path] [--json]",
			revoke: "heli grant revoke <grant-id> [path]",
		},
	},
	install: {
		usage: "heli install [path] [--force]",
		summary: "Install the embedded/portable Heli distribution into a workspace.",
	},
	update: {
		usage: "heli update [path] [--reset-state]",
		summary: "Update a linked or embedded Heli workspace while preserving user state by default.",
	},
	migrate: {
		usage: "heli migrate [workspace-path] [--root <dir>] [--discover] [--depth N] [--dry-run] [--json]",
		summary: "Migrate linked workspaces discovered from the machine-global locator registry to the currently installed Heli runtime. --root filters a development tree; --discover scans that tree for .heli/workspace.json when registry entries are missing.",
	},
	uninstall: {
		usage: "heli uninstall [path]",
		summary: "Remove a linked binding and/or embedded Heli workspace files. Host integrations are unchanged.",
	},
	target: {
		usage: "heli target <list|show|set|clear> [options] [path]",
		summary: "Inspect or select the current repository target.",
		subcommands: {
			list: "heli target list [path] [--json]",
			show: "heli target show [path] [--json]",
			set: "heli target set <repo-name-or-path> [--confirm] [path] [--json]",
			clear: "heli target clear [path] [--json]",
		},
	},
	status: {
		usage: "heli status [path] [--json]",
		summary: "Show current workspace layout, tasks/work records, sessions, and writer authority.",
	},
	resume: {
		usage: "heli resume [path] [--json]",
		summary: "Build a read-only continuation packet for handing work to another host/session.",
	},
	doctor: {
		usage: "heli doctor [path] [--repair] [--json]",
		summary: "Run local workspace health checks. --repair releases closed, orphaned, and unknown stale authority and normalizes safe path aliases. It does not take a live writer.",
	},
	governance: {
		usage: "heli governance <show|set> [flow|strict|observe] [path]",
		summary: "Show or set the governance profile. flow is the default: valid work continues and only a proven live conflict or destructive boundary blocks. strict keeps the older fail-closed writer gate. observe records decisions without blocking ordinary writes.",
		subcommands: {
			show: "heli governance show [path] [--json]",
			set: "heli governance set <flow|strict|observe> [path] [--json]",
		},
	},
	yolo: {
		usage: "heli yolo <on|off|status> [path] [--hours N]",
		summary: "Manage the local reduced-protection switch. YOLO never bypasses writer/resource ownership.",
		subcommands: {
			on: "heli yolo on [path] [--hours N]",
			off: "heli yolo off [path]",
			status: "heli yolo status [path]",
		},
	},
	task: {
		usage: "heli task <create|list|show|depends|migrate-legacy|claim|release|provenance|complete|takeover> [options] [path]",
		summary: "Manage durable work records and embedded compatibility task authority.",
		subcommands: {
			create: "heli task create <task-id> [--title <text>] [--work-item <key>] [--repo <repo>] [--worktree <path>] [--mode strict|yolo] [--allow-duplicate] [--reuse] [path]",
			list: "heli task list [path] [--json]",
			show: "heli task show <task-id> [path] [--json]",
			depends: "heli task depends <consumer-task> --on <producer-task> --artifact <artifact-name> [path] [--json]",
			"migrate-legacy": "heli task migrate-legacy [--id <task-id>] [path]",
			claim: "heli task claim <task-id> [--mode write|review|observe] [path]",
			release: "heli task release <task-id> [path]",
			provenance: "heli task provenance <task-id> [path]",
			complete: "heli task complete <task-id> [path]",
			takeover: "heli task takeover <task-id> --confirm [path]",
		},
	},
	handoff: {
		usage: "heli handoff <publish|list|show> [options] [path]",
		summary: "Publish or inspect Git-backed artifact handoff metadata.",
		subcommands: {
			publish: "heli handoff publish --task <producer-task> --name <artifact-name> --ref <git-ref> [--path <repo-relative-path>] [path]",
			list: "heli handoff list [path] [--json]",
			show: "heli handoff show <producer-task>/<artifact-name> [path] [--json]",
		},
	},
	diagnosis: {
		usage: "heli diagnosis <show|init|record|route|gate> <task-id> [options] [path]",
		summary: "Store and inspect structured diagnosis evidence for a task.",
		subcommands: {
			show: "heli diagnosis show <task-id> [path] [--json]",
			init: "heli diagnosis init <task-id> --json <object> [path]",
			record: "heli diagnosis record <task-id> --type <failure|evidence|hypothesis|classify|root-cause|checkpoint|decision|run> --json <object> [path]",
			route: "heli diagnosis route <task-id> --json <object> [path]",
			gate: "heli diagnosis gate <task-id> --json <object> [path]",
		},
	},
	session: {
		usage: "heli session <start|attach|transfer-write|status|list|close> [options] [path]",
		summary: "Inspect and manage Heli session lifecycle. Normal host SessionStart is preferred for native hosts.",
		subcommands: {
			start: "heli session start [--task <task-id>] [--mode write|review|observe] [path]",
			attach: "heli session attach <task-id> [--mode write|review|observe] [path]",
			"transfer-write": "heli session transfer-write <child-session-id> [path] --session <parent-session-id>",
			status: "heli session status [path] [--json]",
			list: "heli session list [path] [--json]",
			close: "heli session close [session-id] [path]",
		},
	},
	conflicts: {
		usage: "heli conflicts [--task <task-id>] [path] [--json]",
		summary: "Show task/resource conflicts known to Heli.",
	},
	explain: {
		usage: "heli explain <authority|task|guard|capabilities|decision|config> [options] [path]",
		summary: "Explain Heli's current governance state without changing it.",
		subcommands: {
			authority: "heli explain authority [path] [--json]",
			task: "heli explain task [--task <task-id>] [path] [--json]",
			guard: "heli explain guard [--task <task-id>] [path] [--json]",
			capabilities: "heli explain capabilities [path] [--json]",
			decision: "heli explain decision <decision-id> [--task <task-id>] [path] [--json]",
			config: "heli explain config [path] [--json]",
		},
	},
	trace: {
		usage: "heli trace show --task <task-id> [path] [--json]",
		summary: "Show recorded task governance events. This is not a complete executor audit log.",
		subcommands: {
			show: "heli trace show --task <task-id> [path] [--json]",
		},
	},
	auth: {
		usage: "heli auth <login|logout|status|devices> [options]",
		summary: "Manage optional cloud-sync credentials.",
		subcommands: {
			login: "heli auth login [--url <url>]",
			logout: "heli auth logout",
			status: "heli auth status",
			devices: "heli auth devices [--revoke <device-id>]",
		},
	},
	ws: {
		usage: "heli ws <create|link|unlink|list|versions|delete> [options]",
		summary: "Manage optional cloud-sync workspace metadata.",
		subcommands: {
			create: "heli ws create <name>",
			link: "heli ws link <workspace-id>",
			unlink: "heli ws unlink",
			list: "heli ws list",
			versions: "heli ws versions",
			delete: "heli ws delete <workspace-id>",
		},
	},
	push: {
		usage: "heli push",
		summary: "Push the current linked workspace to optional cloud sync.",
	},
	pull: {
		usage: "heli pull [--version N] [--accept-policy-changes]",
		summary: "Pull optional cloud-sync state. Policy-affecting changes require explicit acceptance.",
	},
	sync: {
		usage: "heli sync [auto|e2e on|off]",
		summary: "Run sync or configure optional cloud-sync behavior.",
	},
	init: {
		usage: "heli init <name> [--dir <path>] [--clone] [--accept-policy-changes]",
		summary: "Create or restore a cloud-linked workspace.",
	},
};

function topLevelHelp() {
	const width = Math.max(...TOP_LEVEL.map(([name]) => name.length));
	const commands = TOP_LEVEL
		.map(([name, summary]) => `  ${name.padEnd(width)}  ${summary}`)
		.join("\n");
	return `Usage: heli <command> [args]

Heli is a governance and coordination layer for coding agents.

Commands:
${commands}

Global options:
  -h, --help     Show help without running the requested command.
  -v, --version  Print the Heli-Harness version.

Help:
  heli help
  heli help <command>
  heli help <command> <subcommand>
  heli <command> --help
  heli <command> <subcommand> --help

Machine-readable output:
  Supported state/query commands accept --json or --output-json where documented.
`;
}

function commandHelp(command, subcommand = null) {
	const spec = COMMANDS[command];
	if (!spec) return null;
	if (subcommand) {
		const usage = spec.subcommands?.[subcommand];
		if (!usage) return null;
		return `Usage: ${usage}

Parent command:
  ${spec.usage}

Help is read-only. Running this help form does not execute \`${command} ${subcommand}\`.
`;
	}
	const subs = spec.subcommands
		? `\nSubcommands:\n${Object.entries(spec.subcommands)
			.map(([name, usage]) => `  ${name.padEnd(16)} ${usage}`)
			.join("\n")}\n`
		: "";
	return `Usage: ${spec.usage}

${spec.summary}
${subs}
Options:
  -h, --help  Show this help without executing the command.
`;
}

export function helpPathForInvocation(command, args = []) {
	const spec = COMMANDS[command];
	if (!spec) return [command];
	const first = args[0];
	if (first && !first.startsWith("-") && spec.subcommands?.[first]) return [command, first];
	return [command];
}

export function hasHelpFlag(args = []) {
	return args.some((arg) => HELP_FLAG_SET.has(arg));
}

export function renderHelp(path = []) {
	if (!path.length) return topLevelHelp();
	return commandHelp(path[0], path[1] || null);
}

export function printHelp(path = []) {
	const output = renderHelp(path);
	if (output) {
		process.stdout.write(output.endsWith("\n") ? output : `${output}\n`);
		return true;
	}
	const topic = path.filter(Boolean).join(" ");
	process.stderr.write(`Unknown Heli help topic: ${topic || "(empty)"}\n`);
	process.stdout.write(topLevelHelp());
	return false;
}
