// GENERATED by scripts/sync-workspace-cli.mjs — edit bin/heli.mjs + lib/cli/ instead.\nimport { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { spawnSync } from "node:child_process";
import { wantsJson, stripOutputFlags, printProtocolResult } from "./output.mjs";
import { protocolOk } from "../protocol/result.mjs";

const HOSTS = Object.freeze({
	codex: { label: "Codex", runtime: "enforced", cli: "codex", automatic: true },
	pi: { label: "Pi", runtime: "enforced", cli: "pi", automatic: true },
	claude: { label: "Claude Code", runtime: "enforced", cli: "claude", automatic: true },
	grok: { label: "Grok Build", runtime: "enforced", cli: "grok", automatic: true },
	opencode: { label: "OpenCode", runtime: "enforced", cli: "opencode", automatic: true },
	kimi: { label: "Kimi Code CLI", runtime: "enforced", cli: "kimi", automatic: true },
	cursor: { label: "Cursor", runtime: "plugin-wired", cli: "cursor", automatic: true },
	axga: { label: "AXGA", runtime: "documented", cli: "axga", automatic: true },
	antigravity: { label: "Antigravity CLI", runtime: "verified-plugin-wired", cli: "antigravity", automatic: "conditional" },
	generic: { label: "Generic adapter", runtime: "documented", cli: null, automatic: false },
});

const KIMI_START = "# --- heli-harness hooks ---";
const KIMI_END = "# --- end heli-harness hooks ---";

function quote(arg) {
	const value = String(arg);
	return /[\s"]/u.test(value) ? '"' + value.replaceAll('"', '\\"') + '"' : value;
}

function run(command, args = [], options = {}) {
	if (process.platform === "win32") {
		const line = [command, ...args].map(quote).join(" ");
		return spawnSync(line, { encoding: "utf8", shell: true, ...options });
	}
	return spawnSync(command, args, { encoding: "utf8", ...options });
}

function commandPresent(command) {
	if (!command) return false;
	const result = run(command, ["--version"]);
	return !(result.error && result.error.code === "ENOENT") && result.status === 0;
}

function textOf(result) {
	return ((result && result.stdout) || "") + "\n" + ((result && result.stderr) || "");
}

function packageVersion(packageRoot) {
	for (const path of [join(packageRoot, "package.json"), join(packageRoot, ".heli-harness", "manifest.json")]) {
		try {
			const value = JSON.parse(readFileSync(path, "utf8")).version;
			if (value) return value;
		} catch {}
	}
	return "unknown";
}

function asset(packageRoot, ...parts) {
	return join(packageRoot, ".heli-harness", "adapters", ...parts);
}

function userHome(env = process.env) {
	return env.HELI_HOST_HOME || homedir();
}

function heliConfigHome(env = process.env) {
	return env.HELI_CONFIG_DIR || join(userHome(env), ".heli");
}

function receiptPath(id, env = process.env) {
	return join(heliConfigHome(env), "hosts", id + ".json");
}

function readJson(path, fallback = null) {
	try {
		return JSON.parse(readFileSync(path, "utf8"));
	} catch {
		return fallback;
	}
}

function writeReceipt(id, version, env = process.env) {
	const path = receiptPath(id, env);
	mkdirSync(dirname(path), { recursive: true });
	writeFileSync(path, JSON.stringify({
		schemaVersion: 1,
		host: id,
		heliVersion: version,
		installedAt: new Date().toISOString(),
		topology: "global-linked",
	}, null, 2) + "\n", "utf8");
	return path;
}

function removeReceipt(id, env = process.env) {
	rmSync(receiptPath(id, env), { force: true });
}

function readManifestVersion(path) {
	const value = readJson(path, null);
	return value && typeof value.version === "string" ? value.version : null;
}

function markerPresent(path, marker) {
	if (!existsSync(path)) return false;
	try {
		return readFileSync(path, "utf8").includes(marker);
	} catch {
		return false;
	}
}

function antigravityDir(env = process.env) {
	return env.HELI_ANTIGRAVITY_PLUGIN_DIR || null;
}

function hostOwnedPaths(id, env = process.env) {
	const home = userHome(env);
	if (id === "grok") return { hookFile: join(home, ".grok", "hooks", "heli-harness.json") };
	if (id === "kimi") {
		const root = env.KIMI_CODE_HOME || join(home, ".kimi-code");
		return { config: join(root, "config.toml") };
	}
	if (id === "opencode") {
		const root = join(home, ".config", "opencode", "plugins");
		return {
			root,
			entry: join(root, "heli-harness.js"),
			bundle: join(root, "heli-harness-bundle"),
			manifest: join(root, "heli-harness-bundle", "plugin.json"),
		};
	}
	if (id === "cursor") {
		const root = join(home, ".cursor", "plugins", "local", "heli-harness");
		return { root, manifest: join(root, ".cursor-plugin", "plugin.json") };
	}
	if (id === "antigravity") {
		const root = antigravityDir(env);
		return root ? { root, manifest: join(root, "plugin.json") } : {};
	}
	return {};
}

function hostInstalledVersion(id, env = process.env) {
	const paths = hostOwnedPaths(id, env);
	if (paths.manifest && existsSync(paths.manifest)) {
		const version = readManifestVersion(paths.manifest);
		if (version) return version;
	}
	const receipt = readJson(receiptPath(id, env), null);
	return receipt && receipt.heliVersion ? receipt.heliVersion : null;
}

export function inspectHost(packageRoot, id, { env = process.env } = {}) {
	const spec = HOSTS[id];
	if (!spec) throw new Error("unknown host: " + id);
	const cliPresent = commandPresent(spec.cli);
	const paths = hostOwnedPaths(id, env);
	let installed = false;
	let detail = "";

	if (id === "codex" && cliPresent) {
		const result = run("codex", ["plugin", "list"]);
		installed = result.status === 0 && /heli-harness@heli-harness\s+installed, enabled/i.test(result.stdout || "");
		detail = installed ? "plugin installed and enabled" : "plugin not detected";
	} else if ((id === "pi" || id === "axga") && cliPresent) {
		const result = run(spec.cli, ["list"]);
		installed = result.status === 0 && /heli-harness/i.test(textOf(result));
		detail = installed ? "Heli package listed by host" : "Heli package not detected";
	} else if (id === "claude" && cliPresent) {
		const result = run("claude", ["plugin", "list"]);
		installed = result.status === 0 && /heli-harness/i.test(textOf(result));
		detail = installed ? "plugin listed by Claude" : "plugin not detected";
	} else if (id === "grok") {
		installed = Boolean(paths.hookFile && existsSync(paths.hookFile));
		detail = installed ? "user hooks present: " + paths.hookFile : "user hooks not detected";
	} else if (id === "kimi") {
		installed = Boolean(paths.config && markerPresent(paths.config, KIMI_START));
		detail = installed ? "Heli hooks present: " + paths.config : "Heli hooks not detected";
	} else if (id === "opencode") {
		installed = Boolean(paths.entry && paths.bundle && existsSync(paths.entry) && existsSync(paths.bundle));
		detail = installed ? "namespaced global plugin present: " + paths.entry : "global plugin not detected";
	} else if (id === "cursor") {
		installed = Boolean(paths.manifest && existsSync(paths.manifest));
		detail = installed ? "local user plugin present: " + paths.manifest : "local user plugin not detected";
	} else if (id === "antigravity") {
		if (!paths.root) detail = "set HELI_ANTIGRAVITY_PLUGIN_DIR to the host plugin directory for managed install/update/remove";
		else {
			installed = Boolean(paths.manifest && existsSync(paths.manifest));
			detail = installed ? "managed plugin present: " + paths.root : "managed plugin directory configured but Heli plugin not detected";
		}
	} else if (id === "generic") {
		detail = "instruction-only adapter; no host-native lifecycle surface";
	}

	const currentVersion = packageVersion(packageRoot);
	const installedVersion = installed ? hostInstalledVersion(id, env) : null;
	const stale = Boolean(installed && installedVersion && currentVersion !== "unknown" && installedVersion !== currentVersion);
	let lifecycleState = installed ? (stale ? "stale" : installedVersion ? "current" : "unknown-version") : "absent";
	if (!cliPresent && spec.cli && !["grok", "kimi", "opencode", "cursor", "antigravity"].includes(id)) lifecycleState = "host-unavailable";
	if (id === "generic") lifecycleState = "manual";
	if (id === "antigravity" && !paths.root) lifecycleState = "manual";

	return {
		id,
		label: spec.label,
		runtime: spec.runtime,
		cliPresent,
		installed,
		automatic: spec.automatic,
		currentVersion,
		installedVersion,
		stale,
		lifecycleState,
		detail,
		runtimeEvidence: "not inferred from installation; start the host in a linked project and run heli explain capabilities",
	};
}

export function inspectHosts(packageRoot, options = {}) {
	return Object.keys(HOSTS).map((id) => inspectHost(packageRoot, id, options));
}

function step(command, args, { allowAlready = false, allowMissing = false } = {}) {
	const result = run(command, args);
	const output = textOf(result).trim();
	if (result.status === 0) return { ok: true, command: [command, ...args], output };
	if (allowAlready && /already|exists|installed|up.?to.?date/i.test(output)) {
		return { ok: true, command: [command, ...args], output, already: true };
	}
	if (allowMissing && /not found|not installed|does not exist|unknown plugin/i.test(output)) {
		return { ok: true, command: [command, ...args], output, alreadyAbsent: true };
	}
	return { ok: false, command: [command, ...args], output, code: result.status, error: result.error ? result.error.message : null };
}

function copyContents(source, destination) {
	mkdirSync(destination, { recursive: true });
	for (const name of readdirSync(source)) {
		cpSync(join(source, name), join(destination, name), { recursive: true, force: true });
	}
}

function installOpenCode(source, paths) {
	mkdirSync(paths.root, { recursive: true });
	rmSync(paths.bundle, { recursive: true, force: true });
	cpSync(source, paths.bundle, { recursive: true, force: true });
	const wrapper = 'export { default } from "./heli-harness-bundle/heli-harness.js";\nexport * from "./heli-harness-bundle/heli-harness.js";\n';
	writeFileSync(paths.entry, wrapper, "utf8");
}

function removeKimiBlock(path) {
	if (!existsSync(path)) return false;
	const original = readFileSync(path, "utf8");
	const start = original.indexOf(KIMI_START);
	if (start < 0) return false;
	let end = original.indexOf(KIMI_END, start);
	if (end >= 0) end += KIMI_END.length;
	else end = original.length;
	const next = (original.slice(0, start).trimEnd() + "\n" + original.slice(end).trimStart()).trimEnd() + "\n";
	writeFileSync(path, next, "utf8");
	return true;
}

function executeAction(action, args, env) {
	try {
		if (action === "copy-dir") {
			rmSync(args[1], { recursive: true, force: true });
			copyContents(args[0], args[1]);
			return { ok: true, command: [action, ...args] };
		}
		if (action === "opencode-install") {
			installOpenCode(args[0], hostOwnedPaths("opencode", env));
			return { ok: true, command: [action, args[0]] };
		}
		if (action === "remove-dir") {
			rmSync(args[0], { recursive: true, force: true });
			return { ok: true, command: [action, args[0]] };
		}
		if (action === "remove-file") {
			rmSync(args[0], { force: true });
			return { ok: true, command: [action, args[0]] };
		}
		if (action === "remove-kimi-block") {
			const changed = removeKimiBlock(args[0]);
			return { ok: true, command: [action, args[0]], alreadyAbsent: !changed };
		}
	} catch (error) {
		return { ok: false, command: [action, ...args], error: error.message };
	}
	return null;
}

export function planHostInstall(packageRoot, id, { env = process.env } = {}) {
	const version = packageVersion(packageRoot);
	const paths = hostOwnedPaths(id, env);
	switch (id) {
		case "codex":
			return [
				["codex", "plugin", "marketplace", "add", "KJ-AIML/heli-harness"],
				["codex", "plugin", "add", "heli-harness@heli-harness"],
			];
		case "pi":
			return [["pi", "install", "git:github.com/KJ-AIML/heli-harness@v" + version]];
		case "axga":
			return [["axga", "install", "git:github.com/KJ-AIML/heli-harness@v" + version]];
		case "claude":
			return [["claude", "plugin", "install", asset(packageRoot, "claude-plugin")]];
		case "grok":
			return [
				[process.execPath, asset(packageRoot, "grok-plugin", "install-user-hooks.mjs")],
				["grok", "plugin", "install", asset(packageRoot, "grok-plugin"), "--trust"],
			];
		case "kimi":
			return [
				[process.execPath, asset(packageRoot, "kimi-plugin", "install-user-hooks.mjs")],
				["kimi", "doctor", "config"],
			];
		case "opencode":
			return [["opencode-install", asset(packageRoot, "opencode-plugin")]];
		case "cursor":
			return [["copy-dir", asset(packageRoot, "cursor-plugin", "plugins", "heli-harness"), paths.root]];
		case "antigravity":
			return paths.root ? [["copy-dir", asset(packageRoot, "antigravity-plugin"), paths.root]] : [];
		case "generic":
			return [];
		default:
			throw new Error("unknown host: " + id);
	}
}

export function planHostRemove(packageRoot, id, { env = process.env } = {}) {
	const paths = hostOwnedPaths(id, env);
	switch (id) {
		case "codex":
			return [
				["codex", "plugin", "remove", "heli-harness@heli-harness"],
				["codex", "plugin", "marketplace", "remove", "heli-harness"],
			];
		case "pi": return [["pi", "remove", "heli-harness"]];
		case "axga": return [["axga", "remove", "heli-harness"]];
		case "claude": return [["claude", "plugin", "uninstall", "heli-harness"]];
		case "grok":
			return [
				["remove-file", paths.hookFile],
				["grok", "plugin", "uninstall", "heli-harness"],
			];
		case "kimi": return [["remove-kimi-block", paths.config]];
		case "opencode":
			return [["remove-file", paths.entry], ["remove-dir", paths.bundle]];
		case "cursor": return [["remove-dir", paths.root]];
		case "antigravity": return paths.root ? [["remove-dir", paths.root]] : [];
		case "generic": return [];
		default: throw new Error("unknown host: " + id);
	}
}

function runPlan(plan, { env = process.env, remove = false } = {}) {
	const steps = [];
	for (const [command, ...args] of plan) {
		const custom = executeAction(command, args, env);
		const result = custom || step(command, args, {
			allowAlready: !remove,
			allowMissing: remove,
		});
		steps.push(result);
		if (!result.ok) return { ok: false, steps };
	}
	return { ok: true, steps };
}

export function installHost(packageRoot, id, { dryRun = false, force = false, env = process.env } = {}) {
	const spec = HOSTS[id];
	if (!spec) throw new Error("unknown host: " + id);
	const before = inspectHost(packageRoot, id, { env });
	const plan = planHostInstall(packageRoot, id, { env });
	if (!plan.length) {
		return { id, ok: true, skipped: true, reason: before.detail || "manual integration", before, steps: [] };
	}
	if (!before.cliPresent && spec.cli && !["opencode", "cursor", "antigravity"].includes(id)) {
		return { id, ok: false, skipped: true, reason: spec.label + " CLI not found on PATH", before, steps: [] };
	}
	if (!force && before.installed && before.lifecycleState === "current") {
		return { id, ok: true, already: true, before, after: before, steps: [] };
	}
	if (dryRun) return { id, ok: true, dryRun: true, plan, before };
	const executed = runPlan(plan, { env });
	if (!executed.ok) return { id, ok: false, before, after: inspectHost(packageRoot, id, { env }), steps: executed.steps };
	writeReceipt(id, packageVersion(packageRoot), env);
	const after = inspectHost(packageRoot, id, { env });
	return { id, ok: after.installed || ["grok", "kimi"].includes(id), before, after, steps: executed.steps };
}

export function updateHost(packageRoot, id, options = {}) {
	return installHost(packageRoot, id, { ...options, force: true });
}

export function repairHost(packageRoot, id, options = {}) {
	return installHost(packageRoot, id, { ...options, force: true });
}

export function removeHost(packageRoot, id, { dryRun = false, env = process.env } = {}) {
	const spec = HOSTS[id];
	if (!spec) throw new Error("unknown host: " + id);
	const before = inspectHost(packageRoot, id, { env });
	const plan = planHostRemove(packageRoot, id, { env });
	if (!plan.length) {
		return { id, ok: true, skipped: true, reason: before.detail || "manual integration", before, steps: [] };
	}
	if (dryRun) return { id, ok: true, dryRun: true, plan, before };
	const executablePlan = plan.filter(([command]) => {
		if (["remove-file", "remove-dir", "remove-kimi-block"].includes(command)) return true;
		return commandPresent(command);
	});
	const executed = runPlan(executablePlan, { env, remove: true });
	if (!executed.ok) return { id, ok: false, before, after: inspectHost(packageRoot, id, { env }), steps: executed.steps };
	removeReceipt(id, env);
	const after = inspectHost(packageRoot, id, { env });
	return { id, ok: !after.installed, before, after, steps: executed.steps };
}

function parse(args) {
	const clean = stripOutputFlags(args);
	const flags = { dryRun: false };
	const positional = [];
	for (const item of clean) {
		if (item === "--dry-run") flags.dryRun = true;
		else positional.push(item);
	}
	return { positional, flags };
}

function selectedIds(requested) {
	if (!requested.length || requested.includes("all")) return Object.keys(HOSTS);
	for (const id of requested) if (!HOSTS[id]) throw new Error("unknown host: " + id);
	return requested;
}

function renderOperation(items, verb) {
	for (const item of items) {
		if (item.skipped) console.log("- " + item.id + ": skipped — " + item.reason);
		else if (item.dryRun) console.log("- " + item.id + ": dry-run — " + item.plan.map((p) => p.join(" ")).join(" ; "));
		else if (item.already) console.log("- " + item.id + ": already current");
		else console.log("- " + item.id + ": " + (item.ok ? verb : "FAILED"));
	}
}

export function runHost(packageRoot, args = []) {
	const json = wantsJson(args);
	const { positional, flags } = parse(args);
	const sub = positional[0] || "status";

	if (sub === "list" || sub === "status") {
		const hosts = inspectHosts(packageRoot);
		const result = protocolOk("host.status", { hosts });
		if (json) printProtocolResult(result);
		else {
			console.log("Heli host integrations:");
			for (const host of hosts) {
				const mark = host.lifecycleState === "current" ? "✓" : host.lifecycleState === "stale" ? "!" : host.cliPresent ? "○" : "–";
				const version = host.installedVersion ? " version=" + host.installedVersion : "";
				console.log("  " + mark + " " + host.label.padEnd(16) + " state=" + host.lifecycleState + version + " runtime=" + host.runtime);
				if (host.detail) console.log("      " + host.detail);
			}
			console.log("");
			console.log("Installation state is not runtime proof. Open a linked project in the host, then run: heli explain capabilities");
		}
		return result;
	}

	const ids = selectedIds(positional.slice(1));
	let items;
	let commandName;
	let verb;
	if (sub === "install") {
		items = ids.map((id) => installHost(packageRoot, id, { dryRun: flags.dryRun }));
		commandName = "host.install";
		verb = "installed/verified";
	} else if (sub === "update") {
		items = ids.map((id) => updateHost(packageRoot, id, { dryRun: flags.dryRun }));
		commandName = "host.update";
		verb = "updated/verified";
	} else if (sub === "repair") {
		items = ids.map((id) => repairHost(packageRoot, id, { dryRun: flags.dryRun }));
		commandName = "host.repair";
		verb = "repaired/verified";
	} else if (sub === "remove" || sub === "uninstall") {
		items = ids.map((id) => removeHost(packageRoot, id, { dryRun: flags.dryRun }));
		commandName = "host.remove";
		verb = "removed";
	} else {
		throw new Error("Usage: heli host status|list|install|update|repair|remove [all|codex|pi|claude|grok|opencode|kimi|cursor|axga|antigravity|generic] [--dry-run]");
	}

	const result = protocolOk(commandName, { hosts: items });
	if (json) printProtocolResult(result);
	else {
		renderOperation(items, verb);
		console.log("");
		console.log("Check lifecycle state: heli host status");
	}
	if (items.some((item) => item.ok === false)) process.exitCode = 1;
	return result;
}
