// GENERATED by scripts/sync-workspace-cli.mjs — edit bin/heli.mjs + lib/cli/ instead.
/**
 * Privileged Heli commands (scoped grants, YOLO) must come from a human.
 * A coding agent's shell tool runs without a terminal, so both stdin and stdout
 * must be TTYs. Tests inject `terminal` explicitly as a function argument;
 * there is deliberately no environment-variable bypass an agent could set.
 */
export function realTerminal() {
	return { stdin: process.stdin.isTTY === true, stdout: process.stdout.isTTY === true };
}

export function assertHumanTerminal(command, terminal = realTerminal()) {
	if (terminal?.stdin === true && terminal?.stdout === true) return;
	const windowsHint = process.platform === "win32"
		? " In a Git Bash (mintty) window, run it from Windows Terminal or PowerShell instead, or prefix it with `winpty`."
		: "";
	const error = new Error(
		`\`${command}\` must be run by a human in an interactive terminal (stdin and stdout must be a TTY). ` +
			`A coding agent cannot approve its own actions: ask the user to run \`${command}\` in their own terminal.${windowsHint}`,
	);
	error.code = "HUMAN_TERMINAL_REQUIRED";
	throw error;
}
