// GENERATED by scripts/sync-workspace-cli.mjs — edit bin/heli.mjs + lib/cli/ instead.
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import {
	createTask,
	listTasks,
	readTask,
	readTaskMarkdown,
	migrateLegacyTask,
	writeConcurrentProjection,
} from "../adapters/shared/concurrency/task.mjs";
import {
	acquireWriteLease,
	releaseWriteLease,
	takeoverWriteLease,
	readLease,
	isLeaseExpired,
} from "../adapters/shared/concurrency/lease.mjs";
import { createSession, attachSession, readSession } from "../adapters/shared/concurrency/session.mjs";
import { writeBinding } from "../adapters/shared/concurrency/binding.mjs";
import { findWorkspaceRoot, resolveWorktreeRoot } from "../adapters/shared/concurrency/paths.mjs";
import { detectPathClaimConflicts } from "../adapters/shared/concurrency/conflicts.mjs";
import {
	authorizeAction,
	classifyHypothesis,
	establishRootCause,
	recordCheckpoint,
	recordDecision,
	recordEvidence,
	recordRun,
	readDiagnosis,
	routeDiagnosis,
	setHypothesis,
	startDiagnosis,
} from "../adapters/shared/concurrency/diagnosis.mjs";
import { listActiveTasks } from "../adapters/shared/concurrency/task.mjs";
import { listRepos, showTarget, setTarget, clearTarget } from "./target.mjs";
import { protocolOk, protocolError } from "../protocol/result.mjs";
import { printProtocolResult } from "./output.mjs";
import {
	claimTaskTransition,
	releaseTaskTransition,
	takeoverTaskTransition,
	completeTaskTransition,
} from "../adapters/shared/concurrency/task-transitions.mjs";

function requireWorkspace(cwd) {
	const root = findWorkspaceRoot(cwd);
	if (!root) {
		const error = new Error(`No Heli workspace found from ${cwd}`);
		error.code = "WORKSPACE_NOT_FOUND";
		throw error;
	}
	return root;
}

function parse(args, { payload = false } = {}) {
	const flags = {};
	const positional = [];
	for (let i = 0; i < args.length; i += 1) {
		const value = args[i];
		if (value === "--json" || value === "--output-json") flags.outputJson = true;
		else if (value === "--payload-json" && args[i + 1]) flags.payloadJson = args[++i];
		else if (["--mode", "--title", "--work-item", "--repo", "--worktree", "--id", "--session", "--host", "--type", "--route", "--reason"].includes(value) && args[i + 1]) flags[value.slice(2)] = args[++i];
		else if (["--allow-duplicate", "--reuse", "--confirm", "--force", "--yolo"].includes(value)) flags[value.slice(2)] = true;
		else if (value.startsWith("--")) flags[value.slice(2)] = true;
		else positional.push(value);
	}
	if (payload && flags.payloadJson) {
		try {
			flags.payload = JSON.parse(flags.payloadJson);
			if (!flags.payload || typeof flags.payload !== "object" || Array.isArray(flags.payload)) throw new Error("payload must be an object");
		} catch (error) {
			const wrapped = new Error(`invalid --payload-json: ${error.message}`);
			wrapped.code = "INVALID_JSON_PAYLOAD";
			throw wrapped;
		}
	} else flags.payload = {};
	return { flags, positional };
}

function emit(command, data, { ok = true, warnings = [], errors = [] } = {}) {
	const result = ok ? protocolOk(command, data, { warnings }) : { ...protocolError(command, errors[0]?.code || "COMMAND_FAILED", errors[0]?.message || "command failed"), data };
	printProtocolResult(result);
	return result;
}

export function runTargetMachine(args = []) {
	const clean = args.filter((item) => item !== "--json" && item !== "--output-json");
	const [sub = "show", ...rest] = clean;
	const confirm = rest.includes("--confirm");
	const positional = rest.filter((item) => item !== "--confirm");
	if (sub === "list") {
		const cwd = positional[0] || process.cwd();
		return emit("target.list", { workspaceRoot: findWorkspaceRoot(cwd) || cwd, ...listRepos(cwd) });
	}
	if (sub === "show") {
		const cwd = positional[0] || process.cwd();
		return emit("target.show", { workspaceRoot: findWorkspaceRoot(cwd) || cwd, ...showTarget(cwd) });
	}
	if (sub === "set") {
		const selector = positional[0];
		if (!selector) throw Object.assign(new Error("target selector required"), { code: "TARGET_SELECTOR_REQUIRED" });
		const cwd = positional[1] || process.cwd();
		const result = setTarget(cwd, selector, { confirm });
		return emit("target.set", result, { warnings: result.needsConfirm ? [{ code: "TARGET_CONFIRM_REQUIRED", currentRepo: result.currentRepo, newRepo: result.newRepo }] : [] });
	}
	if (sub === "clear") {
		const cwd = positional[0] || process.cwd();
		return emit("target.clear", { target: clearTarget(cwd) });
	}
	throw Object.assign(new Error(`unknown target command: ${sub}`), { code: "UNKNOWN_TARGET_COMMAND" });
}

export function runConflictsMachine(args = []) {
	let taskId = null;
	let cwd = process.cwd();
	for (let i = 0; i < args.length; i += 1) {
		if (args[i] === "--task" && args[i + 1]) taskId = args[++i];
		else if (args[i] !== "--json" && args[i] !== "--output-json" && !args[i].startsWith("-")) cwd = args[i];
	}
	const workspaceRoot = requireWorkspace(cwd);
	const activeTasks = listActiveTasks(workspaceRoot).map((task) => ({ taskId: task.taskId, owns: task.pathClaims?.owns || [] }));
	const conflicts = detectPathClaimConflicts(workspaceRoot, { taskId });
	return emit("conflicts", { workspaceRoot, taskId, activeTasks, conflicts });
}

export function runDiagnosisMachine(args = []) {
	const [sub, ...rest] = args.filter((item) => item !== "--output-json");
	const { flags, positional } = parse(rest, { payload: true });
	const taskId = positional[0];
	if (!taskId) throw Object.assign(new Error("task id required"), { code: "TASK_REQUIRED" });
	const cwd = positional[1] || process.cwd();
	const workspaceRoot = requireWorkspace(cwd);
	const sessionId = flags.session || process.env.HELI_SESSION_ID || null;
	if (sub === "show") return emit("diagnosis.show", { workspaceRoot, taskId, diagnosis: readDiagnosis(workspaceRoot, taskId) });
	let result;
	if (sub === "init") result = startDiagnosis(workspaceRoot, taskId, flags.payload, { sessionId });
	else if (sub === "route") result = routeDiagnosis(workspaceRoot, taskId, { ...flags.payload, route: flags.route, reason: flags.reason }, { sessionId });
	else if (sub === "gate") {
		result = authorizeAction(workspaceRoot, taskId, flags.payload, { sessionId });
		const envelope = emit("diagnosis.gate", { workspaceRoot, taskId, ...result });
		if (!result.allowed) process.exitCode = 2;
		return envelope;
	} else if (sub === "record") {
		const type = String(flags.type || "").toLowerCase();
		const options = { sessionId };
		if (type === "failure" || type === "run") result = recordRun(workspaceRoot, taskId, type === "failure" ? { ...flags.payload, status: flags.payload.status || "failed" } : flags.payload, options);
		else if (type === "evidence") result = recordEvidence(workspaceRoot, taskId, flags.payload, options);
		else if (type === "hypothesis") result = setHypothesis(workspaceRoot, taskId, flags.payload, options);
		else if (type === "classify") result = classifyHypothesis(workspaceRoot, taskId, flags.payload, options);
		else if (type === "root-cause" || type === "root_cause") result = establishRootCause(workspaceRoot, taskId, flags.payload, options);
		else if (type === "checkpoint") result = recordCheckpoint(workspaceRoot, taskId, flags.payload, options);
		else if (type === "decision") result = recordDecision(workspaceRoot, taskId, flags.payload, options);
		else throw Object.assign(new Error("record requires a supported --type"), { code: "INVALID_DIAGNOSIS_TRANSITION" });
	} else throw Object.assign(new Error(`unknown diagnosis command: ${sub}`), { code: "UNKNOWN_DIAGNOSIS_COMMAND" });
	return emit(`diagnosis.${sub}`, { workspaceRoot, taskId, diagnosis: result });
}

export function runTaskMachine(args = []) {
	const [sub, ...rest] = args;
	const { flags, positional } = parse(rest);
	if (sub === "list") {
		const cwd = positional[0] || process.cwd();
		const workspaceRoot = requireWorkspace(cwd);
		const tasks = listTasks(workspaceRoot).map((task) => {
			const lease = readLease(workspaceRoot, task.taskId);
			return { ...task, leaseState: !lease ? "none" : lease.invalid ? "invalid" : isLeaseExpired(lease) ? "stale" : "active", writerSessionId: lease?.sessionId || null };
		});
		return emit("task.list", { workspaceRoot, tasks });
	}
	if (sub === "show") {
		const taskId = positional[0];
		if (!taskId) throw Object.assign(new Error("task id required"), { code: "TASK_REQUIRED" });
		const cwd = positional[1] || process.cwd();
		const workspaceRoot = requireWorkspace(cwd);
		const task = readTask(workspaceRoot, taskId);
		if (!task) throw Object.assign(new Error(`task not found: ${taskId}`), { code: "TASK_NOT_FOUND" });
		return emit("task.show", { workspaceRoot, task, markdown: readTaskMarkdown(workspaceRoot, taskId), lease: readLease(workspaceRoot, taskId) });
	}
	if (sub === "create") {
		const taskId = positional[0] || flags.id;
		if (!taskId) throw Object.assign(new Error("task id required"), { code: "TASK_REQUIRED" });
		const cwd = positional[1] || process.cwd();
		const workspaceRoot = requireWorkspace(cwd);
		const worktreePath = flags.worktree || resolveWorktreeRoot(cwd);
		let task;
		let reused = false;
		try {
			task = createTask(workspaceRoot, {
				taskId,
				title: flags.title || taskId,
				workItemKey: flags["work-item"] || taskId,
				repositoryId: flags.repo || "",
				worktreePath,
				mode: flags.yolo ? "yolo" : flags.mode || "strict",
				allowDuplicate: Boolean(flags["allow-duplicate"]),
			});
		} catch (error) {
			if (error.code === "TASK_EXISTS" && flags.reuse && error.task) {
				task = error.task;
				reused = true;
			} else throw error;
		}
		writeConcurrentProjection(workspaceRoot);
		return emit("task.create", { workspaceRoot, task, reused });
	}
	if (sub === "migrate-legacy") {
		const taskId = flags.id || positional[0];
		if (!taskId) throw Object.assign(new Error("task id required"), { code: "TASK_REQUIRED" });
		const cwd = positional.find((item) => item !== taskId) || process.cwd();
		const workspaceRoot = requireWorkspace(cwd);
		const task = migrateLegacyTask(workspaceRoot, taskId, { title: flags.title, repositoryId: flags.repo });
		return emit("task.migrate-legacy", { workspaceRoot, task });
	}
	if (sub === "claim") {
		const taskId = positional[0];
		if (!taskId) throw Object.assign(new Error("task id required"), { code: "TASK_REQUIRED" });
		const cwd = positional[1] || process.cwd();
		const workspaceRoot = requireWorkspace(cwd);
		const result = claimTaskTransition(workspaceRoot, {
			taskId,
			sessionId: flags.session || process.env.HELI_SESSION_ID || null,
			host: flags.host || "cli",
			mode: flags.mode || "write",
			worktreePath: resolveWorktreeRoot(cwd),
		});
		return emit("task.claim", result);
	}
	if (sub === "release") {
		const taskId = positional[0] || null;
		const cwd = positional[1] || process.cwd();
		const workspaceRoot = requireWorkspace(cwd);
		const result = releaseTaskTransition(workspaceRoot, {
			taskId,
			sessionId: flags.session || process.env.HELI_SESSION_ID || null,
			force: Boolean(flags.force || flags.confirm),
		});
		return emit("task.release", result);
	}
	if (sub === "takeover") {
		const taskId = positional[0];
		if (!taskId) throw Object.assign(new Error("task id required"), { code: "TASK_REQUIRED" });
		const cwd = positional[1] || process.cwd();
		const workspaceRoot = requireWorkspace(cwd);
		const result = takeoverTaskTransition(workspaceRoot, {
			taskId,
			sessionId: flags.session || process.env.HELI_SESSION_ID || null,
			host: flags.host || "cli",
			worktreePath: resolveWorktreeRoot(cwd),
			confirm: Boolean(flags.confirm),
		});
		return emit("task.takeover", result);
	}
	if (sub === "complete") {
		const taskId = positional[0];
		if (!taskId) throw Object.assign(new Error("task id required"), { code: "TASK_REQUIRED" });
		const cwd = positional[1] || process.cwd();
		const workspaceRoot = requireWorkspace(cwd);
		const result = completeTaskTransition(workspaceRoot, {
			taskId,
			sessionId: flags.session || process.env.HELI_SESSION_ID || null,
		});
		return emit("task.complete", result);
	}
	if (sub === "provenance") {
		const taskId = positional[0];
		if (!taskId) throw Object.assign(new Error("task id required"), { code: "TASK_REQUIRED" });
		const cwd = positional[1] || process.cwd();
		const workspaceRoot = requireWorkspace(cwd);
		const task = readTask(workspaceRoot, taskId);
		if (!task) throw Object.assign(new Error(`task not found: ${taskId}`), { code: "TASK_NOT_FOUND" });
		const path = join(workspaceRoot, ".heli-harness", "tasks", taskId, "events.jsonl");
		const events = existsSync(path) ? readFileSync(path, "utf8").split(/\r?\n/).filter(Boolean).map((line) => { try { return JSON.parse(line); } catch { return { malformed: true, raw: line }; } }) : [];
		return emit("task.provenance", { workspaceRoot, task, lease: readLease(workspaceRoot, taskId), events });
	}
	throw Object.assign(new Error(`machine JSON not implemented for task ${sub}`), { code: "UNSUPPORTED_MACHINE_COMMAND" });
}
