// GENERATED by scripts/sync-workspace-cli.mjs — edit bin/heli.mjs + lib/cli/ instead.
import { resolve } from "node:path";
import { findWorkspaceRoot } from "../adapters/shared/concurrency/paths.mjs";
import {
	discoverWorkspaceRepos,
	listWorkspaceRepos,
	registerWorkspaceRepo,
	removeWorkspaceRepo,
} from "../adapters/shared/concurrency/index.mjs";
import { protocolOk } from "../protocol/result.mjs";
import { printProtocolResult, stripOutputFlags, wantsJson } from "./output.mjs";

function requiredWorkspace(cwd) {
	const root = findWorkspaceRoot(cwd);
	if (root) return root;
	const error = new Error(`No Heli workspace found from ${cwd}`);
	error.code = "WORKSPACE_NOT_FOUND";
	throw error;
}

function parseOptions(args) {
	const values = stripOutputFlags(args);
	const positional = [];
	let name = null;
	let profile = "";
	let maxDepth = 4;
	for (let i = 0; i < values.length; i += 1) {
		const value = values[i];
		if (value === "--name" && values[i + 1]) name = values[++i];
		else if (value === "--profile" && values[i + 1]) profile = values[++i];
		else if (value === "--depth" && values[i + 1]) {
			const parsed = Number.parseInt(values[++i], 10);
			if (Number.isInteger(parsed) && parsed >= 0 && parsed <= 12) maxDepth = parsed;
			else {
				const error = new Error("--depth must be an integer from 0 to 12");
				error.code = "INVALID_DEPTH";
				throw error;
			}
		} else if (!value.startsWith("--")) positional.push(value);
	}
	return { positional, name, profile, maxDepth };
}

function emit(command, data, json) {
	if (json) {
		printProtocolResult(protocolOk(command, data));
		return data;
	}
	return data;
}

export function runRepo(args = []) {
	const json = wantsJson(args);
	const [subcommand = "list", ...rest] = stripOutputFlags(args);
	const { positional, name, profile, maxDepth } = parseOptions(rest);
	const cwd = process.cwd();

	switch (subcommand) {
		case "list": {
			const explicit = positional[0] ? resolve(positional[0]) : cwd;
			const workspaceRoot = requiredWorkspace(explicit);
			const repos = listWorkspaceRepos(workspaceRoot);
			const data = { workspaceRoot, repos };
			emit("repo.list", data, json);
			if (!json) {
				console.log(`Workspace: ${workspaceRoot}`);
				if (!repos.length) console.log("Registered repos: none");
				else {
					console.log(`Registered repos: ${repos.length}`);
					for (const repo of repos) {
						console.log(
							`- ${repo.name} id=${repo.id} path=${repo.path}${repo.profile ? ` profile=${repo.profile}` : ""}${repo.defaultTarget ? " default" : ""}`,
						);
					}
				}
			}
			return data;
		}
		case "add": {
			const target = resolve(positional[0] || cwd);
			const workspaceRoot = requiredWorkspace(target);
			const result = registerWorkspaceRepo(workspaceRoot, target, { name, profile });
			emit("repo.add", result, json);
			if (!json) {
				console.log(`${result.created ? "Registered" : "Updated"} repository ${result.repository.name}`);
				console.log(`  workspace: ${result.workspaceRoot}`);
				console.log(`  path: ${result.repository.path}`);
				console.log("  authority: unchanged");
			}
			return result;
		}
		case "remove": {
			const selector = positional[0];
			if (!selector) {
				const error = new Error("Usage: heli repo remove <id-or-name-or-path> [workspace-path]");
				error.code = "REPO_SELECTOR_REQUIRED";
				throw error;
			}
			const workspacePath = positional[1] ? resolve(positional[1]) : cwd;
			const workspaceRoot = requiredWorkspace(workspacePath);
			const result = removeWorkspaceRepo(workspaceRoot, selector);
			emit("repo.remove", result, json);
			if (!json) {
				console.log(`Removed repository ${result.removed.name} (${result.removed.path})`);
				console.log("  tasks/sessions/authority: unchanged");
			}
			return result;
		}
		case "discover": {
			const searchPath = resolve(positional[0] || cwd);
			const workspaceRoot = requiredWorkspace(searchPath);
			const result = discoverWorkspaceRepos(workspaceRoot, { searchPath, maxDepth });
			emit("repo.discover", result, json);
			if (!json) {
				console.log(`Workspace: ${result.workspaceRoot}`);
				console.log(`Discovered repos: ${result.discovered.length}`);
				for (const repo of result.discovered) console.log(`- ${repo.name} -> ${repo.path}`);
				console.log(`Total registered repos: ${result.repos.length}`);
			}
			return result;
		}
		default: {
			const error = new Error("Usage: heli repo <list|add|remove|discover> [options]");
			error.code = "UNKNOWN_REPO_COMMAND";
			throw error;
		}
	}
}
