// GENERATED by scripts/sync-workspace-cli.mjs — edit bin/heli.mjs + lib/cli/ instead.
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { resolveExecutionContext } from "../adapters/shared/concurrency/resolve.mjs";
import { listActiveTasks, listTasks } from "../adapters/shared/concurrency/task.mjs";
import { listActiveSessions, readSession } from "../adapters/shared/concurrency/session.mjs";
import { readLease, isLeaseExpired } from "../adapters/shared/concurrency/lease.mjs";
import { isConcurrentMode, readWorkspaceSchema } from "../adapters/shared/concurrency/schema.mjs";
import { findWorkspaceRoot, canonicalizePath, pathsFor } from "../adapters/shared/concurrency/paths.mjs";
import {
	readProjectBinding,
	readWorkspaceLock,
	resolveExecutionIdentity,
} from "../adapters/shared/concurrency/project-binding.mjs";
import { projectTaskWorktree, readWorkspaceIndex } from "../adapters/shared/concurrency/portable-targets.mjs";
import { listAllBindings } from "../adapters/shared/concurrency/binding.mjs";
import { protocolOk } from "../protocol/result.mjs";
import { printProtocolResult, stripOutputFlags, wantsJson } from "./output.mjs";

function readJson(path) {
	try {
		return JSON.parse(readFileSync(path, "utf8"));
	} catch {
		return null;
	}
}

function field(text, label) {
	const match = new RegExp(`^${label}:[ \\t]*(.*)$`, "m").exec(text);
	return match ? match[1].trim() : "";
}

function formatLeaseExpiry(lease) {
	if (!lease?.expiresAt) return "n/a";
	const exp = Date.parse(lease.expiresAt);
	if (Number.isNaN(exp)) return lease.expiresAt;
	const ms = exp - Date.now();
	if (ms <= 0) return `expired (${lease.expiresAt})`;
	const h = Math.floor(ms / 3600_000);
	const m = Math.floor((ms % 3600_000) / 60_000);
	return `expires in ${h}h ${m}m (${lease.expiresAt})`;
}

/**
 * Resolve the live worktree for a task using authoritative sources:
 * active write lease → writer session → worktree binding → task metadata → unknown
 */
export function resolveTaskWorktreeProjection(workspaceRoot, task, sessions = null) {
	const warnings = [];
	const allSessions = sessions || listActiveSessions(workspaceRoot);
	const lease = readLease(workspaceRoot, task.taskId);
	const activeLease = lease && !lease.invalid && !isLeaseExpired(lease) ? lease : null;

	let worktree = "";
	let source = "unknown";
	let writer = "none";
	let leaseStatus = "none";
	let worktreeStale = false;
	let worktreeStaleReason = null;

	if (activeLease) {
		writer = activeLease.sessionId || "unknown";
		leaseStatus = `active, ${formatLeaseExpiry(activeLease)}`;
		if (activeLease.worktreePath) {
			worktree = canonicalizePath(activeLease.worktreePath);
			source = "write-lease";
		}
		const writerSession = readSession(workspaceRoot, activeLease.sessionId);
		if (writerSession?.worktreePath) {
			const sessWt = canonicalizePath(writerSession.worktreePath);
			if (worktree && sessWt && worktree !== sessWt) {
				warnings.push(
					`writer session worktree (${sessWt}) differs from lease worktree (${worktree})`,
				);
			}
			if (!worktree && sessWt) {
				worktree = sessWt;
				source = "writer-session";
			}
		}
	} else if (lease?.invalid) {
		leaseStatus = `malformed (${lease.reason || "invalid"})`;
		warnings.push(`malformed lease for ${task.taskId}`);
	} else if (lease && isLeaseExpired(lease)) {
		leaseStatus = `stale, expired ${lease.expiresAt}`;
		writer = lease.sessionId || "none";
		if (lease.worktreePath) {
			worktree = canonicalizePath(lease.worktreePath);
			source = "stale-lease";
			warnings.push("lease is stale — worktree shown from expired lease");
		}
	}

	const reviewers = allSessions.filter(
		(s) =>
			s.taskId === task.taskId &&
			s.status === "active" &&
			(s.mode === "review" || s.mode === "observe"),
	);
	const writerSessions = allSessions.filter(
		(s) => s.taskId === task.taskId && s.status === "active" && s.mode === "write",
	);

	if (!worktree) {
		const writerSess = writerSessions[0] || allSessions.find((s) => s.sessionId === writer);
		if (writerSess?.worktreePath) {
			worktree = canonicalizePath(writerSess.worktreePath);
			source = source === "unknown" ? "active-session" : source;
		}
	}

	if (!worktree) {
		try {
			const bindings = listAllBindings(workspaceRoot);
			const hit = bindings.find((b) => b.taskId === task.taskId && b.canonicalWorktreePath);
			if (hit) {
				worktree = hit.canonicalWorktreePath;
				source = "binding";
			}
		} catch {
			/* ignore */
		}
	}

	const portableProjection = projectTaskWorktree(workspaceRoot, task.target || {}, readWorkspaceIndex(workspaceRoot));
	const metaWt = portableProjection.worktree ? canonicalizePath(portableProjection.worktree) : "";
	if (!worktree && metaWt) {
		worktree = metaWt;
		source = portableProjection.source;
		worktreeStale = portableProjection.stale;
		worktreeStaleReason = portableProjection.reason;
		if (worktreeStale) warnings.push(`task metadata worktree is stale (${worktreeStaleReason || "unknown reason"})`);
	} else if (!worktree && portableProjection.stale) {
		source = portableProjection.source;
		worktreeStale = true;
		worktreeStaleReason = portableProjection.reason;
		warnings.push(`task metadata worktree is stale (${worktreeStaleReason || "unknown reason"})`);
	} else if (worktree && metaWt && worktree !== metaWt && activeLease) {
		warnings.push(`task metadata worktree (${metaWt}) differs from live ${source} (${worktree})`);
	} else if (worktree && portableProjection.stale && activeLease) {
		warnings.push(`task metadata worktree is stale (${portableProjection.reason || "unknown reason"})`);
	}

	const yolo =
		task.yolo?.enabled === true ||
		task.mode === "yolo" ||
		task.mode === "unguarded" ||
		task.mode === "dangerous"
			? "yolo"
			: "strict";

	return {
		taskId: task.taskId,
		status: task.status,
		mode: yolo === "yolo" ? task.mode || "yolo" : task.mode || "strict",
		yoloMode: yolo,
		writer,
		worktree: worktree || "unknown",
		worktreeSource: source,
		worktreeStale,
		worktreeStaleReason,
		repo: task.target?.repositoryId || "",
		branch: task.target?.branch || "",
		leaseStatus,
		reviewerCount: reviewers.length,
		observerCount: allSessions.filter(
			(s) => s.taskId === task.taskId && s.status === "active" && s.mode === "observe",
		).length,
		warnings,
	};
}

function countSkillDirs(skillsRoot) {
	if (!existsSync(skillsRoot)) return 0;
	try {
		return readdirSync(skillsRoot).filter((name) => {
			const p = join(skillsRoot, name);
			return statSync(p).isDirectory() && existsSync(join(p, "SKILL.md"));
		}).length;
	} catch {
		return 0;
	}
}

function skillPackagingStatus(root, linked = false) {
	const workspaceSkills = countSkillDirs(
		linked ? join(root, ".heli", "skills") : join(root, ".heli-harness", "skills"),
	);
	if (linked) {
		return {
			workspaceSkillCount: workspaceSkills,
			codexPluginSkillCount: 0,
			claudePluginSkillCount: 0,
			pluginFilesAvailable: null,
			hostActivation: "global distribution / runtime observation required",
		};
	}
	const codexPluginSkills = countSkillDirs(
		join(root, ".heli-harness", "adapters", "codex-plugin", "skills"),
	);
	const claudePluginSkills = countSkillDirs(
		join(root, ".heli-harness", "adapters", "claude-plugin", "skills"),
	);
	const pluginFilesAvailable =
		existsSync(join(root, ".heli-harness", "adapters", "codex-plugin", ".codex-plugin", "plugin.json")) ||
		existsSync(join(root, ".heli-harness", "adapters", "claude-plugin", ".claude-plugin", "plugin.json"));

	return {
		workspaceSkillCount: workspaceSkills,
		codexPluginSkillCount: codexPluginSkills,
		claudePluginSkillCount: claudePluginSkills,
		pluginFilesAvailable,
		// Disk presence is not live host activation; do not claim skills active.
		hostActivation: "installed / activation not verifiable",
	};
}

export function status(cwd) {
	const heliDir = join(cwd, ".heli-harness");
	const workspaceRoot = findWorkspaceRoot(cwd) || (existsSync(heliDir) ? canonicalizePath(cwd) : null);
	if (!workspaceRoot) {
		return { installed: false };
	}
	const root = workspaceRoot;
	const layout = pathsFor(root);
	const binding = readProjectBinding(root);
	const lock = readWorkspaceLock(root);
	const execution = resolveExecutionIdentity(root);
	const manifest = layout.linked ? null : readJson(join(root, ".heli-harness", "manifest.json"));
	const target = readJson(layout.targetPath);
	const index = readJson(layout.indexPath);
	const schema = readWorkspaceSchema(root);
	const concurrent = schema.mode === "concurrent";
	const skills = skillPackagingStatus(root, layout.linked);

	const base = {
		installed: true,
		version: layout.linked ? lock?.runtime?.version || "unknown" : manifest?.version || "unknown",
		workspaceRoot: root,
		layout: layout.layoutMode,
		workspaceId: binding?.workspaceId || null,
		executionId: execution?.executionId || null,
		operationalRoot: layout.operationalRoot,
		mode: concurrent ? "concurrent" : "legacy",
		targetRepo: target?.targetRepo || "",
		repoCount: Array.isArray(index?.repos) ? index.repos.length : 0,
		indexConfigured: !!index && Array.isArray(index.repos),
		skills,
	};

	if (concurrent) {
		const tasks = listTasks(root);
		const active = listActiveTasks(root);
		const sessions = listActiveSessions(root);
		let writeLeases = 0;
		const taskSummaries = active.map((t) => {
			const proj = resolveTaskWorktreeProjection(root, t, sessions);
			const lease = readLease(root, t.taskId);
			if (lease && !lease.invalid && !isLeaseExpired(lease)) writeLeases++;
			return proj;
		});
		return {
			...base,
			activeTasks: active.length,
			totalTasks: tasks.length,
			activeSessions: sessions.length,
			writeLeases,
			taskSummaries,
		};
	}

	const taskPath = layout.legacyTaskPath;
	const taskText = existsSync(taskPath) ? readFileSync(taskPath, "utf8") : "";
	const taskStatus = taskText ? field(taskText, "Current status") : "";
	const incomplete =
		!!taskStatus &&
		!["complete", "idle", ""].includes(taskStatus.toLowerCase()) &&
		!taskStatus.toLowerCase().includes("none");
	return {
		...base,
		taskStatus,
		failedAttempts: taskText ? field(taskText, "Failed attempts count") : "",
		legacyMultiAgentRisk: incomplete,
	};
}

export function runStatus(args) {
	const json = wantsJson(args);
	const positionalArgs = stripOutputFlags(args);
	const cwd = positionalArgs[0] || process.cwd();
	const result = status(cwd);
	if (json) {
		printProtocolResult(protocolOk("status", result));
		return;
	}
	if (!result.installed) {
		console.log(`No Heli-Harness install found at ${cwd}`);
		return;
	}
	console.log(`Heli-Harness version: ${result.version}`);
	console.log(`Workspace mode: ${result.mode}`);
	console.log(`Workspace layout: ${result.layout || "embedded"}`);
	console.log(`Workspace root: ${result.workspaceRoot}`);
	if (result.workspaceId) console.log(`Workspace ID: ${result.workspaceId}`);
	if (result.executionId) console.log(`Execution ID: ${result.executionId}`);
	console.log(`Target repo: ${result.targetRepo || "not selected"}`);
	console.log(
		result.indexConfigured ? `Registered repos: ${result.repoCount}` : "Workspace index: not configured",
	);
	console.log(
		"Governance enforcement: not verifiable from CLI alone — plugin PreToolUse is live only when the host loaded the Heli plugin this session (SessionStart marker). File/pointer installs without the plugin are advisory.",
	);
	if (result.mode === "legacy") {
		console.log(
			"Legacy multi-agent risk: shared state/current-task.md races if two agents edit it. Parallel work: heli task migrate-legacy --id <id> (or create) → claim write → HELI_SESSION_ID.",
		);
	}
	if (result.skills) {
		console.log(
			`Skill packaging: workspace=${result.skills.workspaceSkillCount} codex-plugin=${result.skills.codexPluginSkillCount} claude-plugin=${result.skills.claudePluginSkillCount}`,
		);
		console.log(
			result.skills.pluginFilesAvailable == null
				? "Host plugin files: managed by global distribution"
				: `Host plugin files: ${result.skills.pluginFilesAvailable ? "available under .heli-harness/adapters/*-plugin" : "missing"}`,
		);
		console.log(`Host skill activation: ${result.skills.hostActivation}`);
	}

	if (result.mode === "concurrent") {
		console.log(`Active tasks: ${result.activeTasks}`);
		console.log(`Active sessions: ${result.activeSessions}`);
		console.log(`Write leases: ${result.writeLeases}`);
		for (const t of result.taskSummaries || []) {
			console.log("");
			console.log(t.taskId);
			console.log(`  status: ${t.status}`);
			console.log(`  writer: ${t.writer}`);
			console.log(`  worktree: ${t.worktree || "unknown"}${t.worktreeStale ? " (stale)" : ""}`);
			console.log(`  worktree source: ${t.worktreeSource || "unknown"}`);
			if (t.worktreeStaleReason) console.log(`  worktree stale reason: ${t.worktreeStaleReason}`);
			console.log(`  lease: ${t.leaseStatus || "none"}`);
			console.log(`  target: ${t.repo || "n/a"}`);
			if (t.branch) console.log(`  branch: ${t.branch}`);
			console.log(`  mode: ${t.mode} (${t.yoloMode || "strict"})`);
			console.log(`  reviewers: ${t.reviewerCount ?? 0}  observers: ${t.observerCount ?? 0}`);
			for (const w of t.warnings || []) {
				console.log(`  warning: ${w}`);
			}
		}
		const ctx = resolveExecutionContext({ cwd, host: "cli", createIfMissing: false });
		if (ctx.sessionId) {
			console.log("");
			console.log(
				`This cwd session: ${ctx.sessionId} task=${ctx.taskId || "unbound"} mode=${ctx.mode || "n/a"} worktree=${ctx.worktreeRoot || "n/a"}`,
			);
		}
		console.log("Current task: see active tasks above (concurrent mode)");
		return;
	}

	if (result.taskStatus) {
		console.log(`Current task status: ${result.taskStatus} (failed attempts: ${result.failedAttempts || "0"})`);
		if (result.legacyMultiAgentRisk) {
			console.log(
				"Warning: incomplete shared current-task.md — second agent will race. Migrate to concurrent for parallel work.",
			);
		}
	} else {
		console.log("Current task: none recorded");
	}
}
