// GENERATED by scripts/sync-workspace-cli.mjs — edit bin/heli.mjs + lib/cli/ instead.
import { existsSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { isLinkedWorkspace, projectConfigDir, unregisterWorkspace } from "../adapters/shared/concurrency/project-binding.mjs";

export function uninstall(parentDir) {
	const parentFull = resolve(parentDir);
	const target = join(parentFull, ".heli-harness");
	const linkedTarget = projectConfigDir(parentFull);
	const removedEmbedded = existsSync(target);
	const removedLinked = isLinkedWorkspace(parentFull);
	if (removedLinked) unregisterWorkspace(parentFull);
	if (removedEmbedded) rmSync(target, { recursive: true, force: true });
	if (removedLinked && existsSync(linkedTarget)) rmSync(linkedTarget, { recursive: true, force: true });
	return { removed: removedEmbedded || removedLinked, target, linkedTarget, removedEmbedded, removedLinked };
}

export function runUninstall(args) {
	const [parentArg] = args;
	const parentDir = parentArg || process.cwd();
	const result = uninstall(parentDir);
	if (!result.removed) {
		console.log(`No installed harness found at ${result.target}`);
		return;
	}
	if (result.removedEmbedded) console.log(`Removed Heli-Harness:\n  ${result.target}`);
	if (result.removedLinked) console.log(`Removed linked project binding:\n  ${result.linkedTarget}`);
	console.log("");
	console.log("Manual cleanup:");
	console.log("  Review any AGENTS.md or CLAUDE.md snippets you created and remove them if no longer needed.");
	console.log("  Repos were not deleted.");
	console.log("  Machine host integrations are unchanged. Remove them with: heli host remove <host>");
}
